// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: system/v1/system.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseSys_SystemLogPage_FullMethodName    = "/v1.base.system.BaseSys/SystemLogPage"
	BaseSys_SystemLogGateway_FullMethodName = "/v1.base.system.BaseSys/SystemLogGateway"
	BaseSys_DepartmentList_FullMethodName   = "/v1.base.system.BaseSys/DepartmentList"
	BaseSys_UserPage_FullMethodName         = "/v1.base.system.BaseSys/UserPage"
)

// BaseSysClient is the client API for BaseSys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseSysClient interface {
	// 系统日志分页
	SystemLogPage(ctx context.Context, in *SystemLogPageRpcInvoke, opts ...grpc.CallOption) (*SystemLogPageRpcRes, error)
	// 记录日志
	SystemLogGateway(ctx context.Context, in *SystemLogGatewayRpcInvoke, opts ...grpc.CallOption) (*SystemLogGatewayRpcRes, error)
	// 部门列表
	DepartmentList(ctx context.Context, in *DepartmentListRpcInvoke, opts ...grpc.CallOption) (*DepartmentListRpcRes, error)
	// 用户分页
	UserPage(ctx context.Context, in *UserPageRpcInvoke, opts ...grpc.CallOption) (*UserPageRpcRes, error)
}

type baseSysClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseSysClient(cc grpc.ClientConnInterface) BaseSysClient {
	return &baseSysClient{cc}
}

func (c *baseSysClient) SystemLogPage(ctx context.Context, in *SystemLogPageRpcInvoke, opts ...grpc.CallOption) (*SystemLogPageRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemLogPageRpcRes)
	err := c.cc.Invoke(ctx, BaseSys_SystemLogPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysClient) SystemLogGateway(ctx context.Context, in *SystemLogGatewayRpcInvoke, opts ...grpc.CallOption) (*SystemLogGatewayRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemLogGatewayRpcRes)
	err := c.cc.Invoke(ctx, BaseSys_SystemLogGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysClient) DepartmentList(ctx context.Context, in *DepartmentListRpcInvoke, opts ...grpc.CallOption) (*DepartmentListRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentListRpcRes)
	err := c.cc.Invoke(ctx, BaseSys_DepartmentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysClient) UserPage(ctx context.Context, in *UserPageRpcInvoke, opts ...grpc.CallOption) (*UserPageRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPageRpcRes)
	err := c.cc.Invoke(ctx, BaseSys_UserPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseSysServer is the server API for BaseSys service.
// All implementations must embed UnimplementedBaseSysServer
// for forward compatibility.
type BaseSysServer interface {
	// 系统日志分页
	SystemLogPage(context.Context, *SystemLogPageRpcInvoke) (*SystemLogPageRpcRes, error)
	// 记录日志
	SystemLogGateway(context.Context, *SystemLogGatewayRpcInvoke) (*SystemLogGatewayRpcRes, error)
	// 部门列表
	DepartmentList(context.Context, *DepartmentListRpcInvoke) (*DepartmentListRpcRes, error)
	// 用户分页
	UserPage(context.Context, *UserPageRpcInvoke) (*UserPageRpcRes, error)
	mustEmbedUnimplementedBaseSysServer()
}

// UnimplementedBaseSysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseSysServer struct{}

func (UnimplementedBaseSysServer) SystemLogPage(context.Context, *SystemLogPageRpcInvoke) (*SystemLogPageRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemLogPage not implemented")
}
func (UnimplementedBaseSysServer) SystemLogGateway(context.Context, *SystemLogGatewayRpcInvoke) (*SystemLogGatewayRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemLogGateway not implemented")
}
func (UnimplementedBaseSysServer) DepartmentList(context.Context, *DepartmentListRpcInvoke) (*DepartmentListRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepartmentList not implemented")
}
func (UnimplementedBaseSysServer) UserPage(context.Context, *UserPageRpcInvoke) (*UserPageRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPage not implemented")
}
func (UnimplementedBaseSysServer) mustEmbedUnimplementedBaseSysServer() {}
func (UnimplementedBaseSysServer) testEmbeddedByValue()                 {}

// UnsafeBaseSysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseSysServer will
// result in compilation errors.
type UnsafeBaseSysServer interface {
	mustEmbedUnimplementedBaseSysServer()
}

func RegisterBaseSysServer(s grpc.ServiceRegistrar, srv BaseSysServer) {
	// If the following call pancis, it indicates UnimplementedBaseSysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseSys_ServiceDesc, srv)
}

func _BaseSys_SystemLogPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemLogPageRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysServer).SystemLogPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSys_SystemLogPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysServer).SystemLogPage(ctx, req.(*SystemLogPageRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSys_SystemLogGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemLogGatewayRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysServer).SystemLogGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSys_SystemLogGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysServer).SystemLogGateway(ctx, req.(*SystemLogGatewayRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSys_DepartmentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentListRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysServer).DepartmentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSys_DepartmentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysServer).DepartmentList(ctx, req.(*DepartmentListRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSys_UserPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPageRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysServer).UserPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSys_UserPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysServer).UserPage(ctx, req.(*UserPageRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseSys_ServiceDesc is the grpc.ServiceDesc for BaseSys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseSys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.base.system.BaseSys",
	HandlerType: (*BaseSysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemLogPage",
			Handler:    _BaseSys_SystemLogPage_Handler,
		},
		{
			MethodName: "SystemLogGateway",
			Handler:    _BaseSys_SystemLogGateway_Handler,
		},
		{
			MethodName: "DepartmentList",
			Handler:    _BaseSys_DepartmentList_Handler,
		},
		{
			MethodName: "UserPage",
			Handler:    _BaseSys_UserPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/system.proto",
}
