// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: system/v1/system.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	pbentity "github.com/vera-byte/vgo/app/admin/api/pbentity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemLogPageRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogPageRpcInvoke) Reset() {
	*x = SystemLogPageRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogPageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogPageRpcInvoke) ProtoMessage() {}

func (x *SystemLogPageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogPageRpcInvoke.ProtoReflect.Descriptor instead.
func (*SystemLogPageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type SystemLogPageRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogPageRpcRes) Reset() {
	*x = SystemLogPageRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogPageRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogPageRpcRes) ProtoMessage() {}

func (x *SystemLogPageRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogPageRpcRes.ProtoReflect.Descriptor instead.
func (*SystemLogPageRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

type SystemLogGatewayRpcInvoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip
	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty" dc:"ip"`
	// action
	Action string `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty" dc:"action"`
	// 参数
	Params string `protobuf:"bytes,3,opt,name=Params,proto3" json:"Params,omitempty" dc:"参数"`
	// 租父ID
	TenantId *int64 `protobuf:"varint,4,opt,name=TenantId,proto3,oneof" json:"TenantId,omitempty" dc:"租父ID"`
	// 用户ID
	UserId *int64 `protobuf:"varint,5,opt,name=UserId,proto3,oneof" json:"UserId,omitempty" dc:"用户ID"`
	// 追踪ID
	TraceId       string `protobuf:"bytes,6,opt,name=TraceId,proto3" json:"TraceId,omitempty" dc:"追踪ID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogGatewayRpcInvoke) Reset() {
	*x = SystemLogGatewayRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogGatewayRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogGatewayRpcInvoke) ProtoMessage() {}

func (x *SystemLogGatewayRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogGatewayRpcInvoke.ProtoReflect.Descriptor instead.
func (*SystemLogGatewayRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *SystemLogGatewayRpcInvoke) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SystemLogGatewayRpcInvoke) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SystemLogGatewayRpcInvoke) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SystemLogGatewayRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogGatewayRpcRes) Reset() {
	*x = SystemLogGatewayRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogGatewayRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogGatewayRpcRes) ProtoMessage() {}

func (x *SystemLogGatewayRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogGatewayRpcRes.ProtoReflect.Descriptor instead.
func (*SystemLogGatewayRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

// 部门List
type DepartmentListRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListRpcInvoke) Reset() {
	*x = DepartmentListRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListRpcInvoke) ProtoMessage() {}

func (x *DepartmentListRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListRpcInvoke.ProtoReflect.Descriptor instead.
func (*DepartmentListRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{4}
}

type DepartmentListRpcRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*DepartmentResultItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentListRpcRes) Reset() {
	*x = DepartmentListRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentListRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentListRpcRes) ProtoMessage() {}

func (x *DepartmentListRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentListRpcRes.ProtoReflect.Descriptor instead.
func (*DepartmentListRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *DepartmentListRpcRes) GetItems() []*DepartmentResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DepartmentResultItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门名称
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" dc:"部门名称"`
	// 排序
	OrderNum int64 `protobuf:"varint,2,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序"`
	// 父ID
	ParentId int64 `protobuf:"varint,3,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"父ID"`
	// 租户ID
	TenantId int64 `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`
	// 部门id
	Id            int64 `protobuf:"varint,5,opt,name=Id,proto3" json:"Id,omitempty" dc:"部门id"`
	UpdateTime    int64 `protobuf:"varint,6,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	CreateTime    int64 `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentResultItem) Reset() {
	*x = DepartmentResultItem{}
	mi := &file_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentResultItem) ProtoMessage() {}

func (x *DepartmentResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentResultItem.ProtoReflect.Descriptor instead.
func (*DepartmentResultItem) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *DepartmentResultItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentResultItem) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *DepartmentResultItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DepartmentResultItem) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DepartmentResultItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentResultItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *DepartmentResultItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type UserPageRpcInvoke struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageReq       *pbentity.PageRpcInvoke `protobuf:"bytes,1,opt,name=PageReq,proto3" json:"PageReq,omitempty"`
	DepartmentIds []int64                 `protobuf:"varint,2,rep,packed,name=DepartmentIds,proto3" json:"DepartmentIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPageRpcInvoke) Reset() {
	*x = UserPageRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageRpcInvoke) ProtoMessage() {}

func (x *UserPageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageRpcInvoke.ProtoReflect.Descriptor instead.
func (*UserPageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *UserPageRpcInvoke) GetPageReq() *pbentity.PageRpcInvoke {
	if x != nil {
		return x.PageReq
	}
	return nil
}

func (x *UserPageRpcInvoke) GetDepartmentIds() []int64 {
	if x != nil {
		return x.DepartmentIds
	}
	return nil
}

type UserPageRpcRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pagination    *pbentity.Pagination    `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	List          []*pbentity.BaseSysUser `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPageRpcRes) Reset() {
	*x = UserPageRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageRpcRes) ProtoMessage() {}

func (x *UserPageRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageRpcRes.ProtoReflect.Descriptor instead.
func (*UserPageRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *UserPageRpcRes) GetPagination() *pbentity.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *UserPageRpcRes) GetList() []*pbentity.BaseSysUser {
	if x != nil {
		return x.List
	}
	return nil
}

var File_system_v1_system_proto protoreflect.FileDescriptor

const file_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/system.proto\x12\x0ev1.base.system\x1a\x1cpbentity/base_sys_user.proto\x1a\x13pbentity/page.proto\"\x18\n" +
	"\x16SystemLogPageRpcInvoke\"\x15\n" +
	"\x13SystemLogPageRpcRes\"\xcb\x01\n" +
	"\x19SystemLogGatewayRpcInvoke\x12\x0e\n" +
	"\x02Ip\x18\x01 \x01(\tR\x02Ip\x12\x16\n" +
	"\x06Action\x18\x02 \x01(\tR\x06Action\x12\x16\n" +
	"\x06Params\x18\x03 \x01(\tR\x06Params\x12\x1f\n" +
	"\bTenantId\x18\x04 \x01(\x03H\x00R\bTenantId\x88\x01\x01\x12\x1b\n" +
	"\x06UserId\x18\x05 \x01(\x03H\x01R\x06UserId\x88\x01\x01\x12\x18\n" +
	"\aTraceId\x18\x06 \x01(\tR\aTraceIdB\v\n" +
	"\t_TenantIdB\t\n" +
	"\a_UserId\"\x18\n" +
	"\x16SystemLogGatewayRpcRes\"\x19\n" +
	"\x17DepartmentListRpcInvoke\"R\n" +
	"\x14DepartmentListRpcRes\x12:\n" +
	"\x05Items\x18\x01 \x03(\v2$.v1.base.system.DepartmentResultItemR\x05Items\"\xce\x01\n" +
	"\x14DepartmentResultItem\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bOrderNum\x18\x02 \x01(\x03R\bOrderNum\x12\x1a\n" +
	"\bParentId\x18\x03 \x01(\x03R\bParentId\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x03R\bTenantId\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\x03R\x02Id\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x06 \x01(\x03R\n" +
	"UpdateTime\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\a \x01(\x03R\n" +
	"CreateTime\"l\n" +
	"\x11UserPageRpcInvoke\x121\n" +
	"\aPageReq\x18\x01 \x01(\v2\x17.pbentity.PageRpcInvokeR\aPageReq\x12$\n" +
	"\rDepartmentIds\x18\x02 \x03(\x03R\rDepartmentIds\"q\n" +
	"\x0eUserPageRpcRes\x124\n" +
	"\n" +
	"Pagination\x18\x01 \x01(\v2\x14.pbentity.PaginationR\n" +
	"Pagination\x12)\n" +
	"\x04List\x18\x02 \x03(\v2\x15.pbentity.BaseSysUserR\x04List2\xfe\x02\n" +
	"\aBaseSys\x12\\\n" +
	"\rSystemLogPage\x12&.v1.base.system.SystemLogPageRpcInvoke\x1a#.v1.base.system.SystemLogPageRpcRes\x12e\n" +
	"\x10SystemLogGateway\x12).v1.base.system.SystemLogGatewayRpcInvoke\x1a&.v1.base.system.SystemLogGatewayRpcRes\x12_\n" +
	"\x0eDepartmentList\x12'.v1.base.system.DepartmentListRpcInvoke\x1a$.v1.base.system.DepartmentListRpcRes\x12M\n" +
	"\bUserPage\x12!.v1.base.system.UserPageRpcInvoke\x1a\x1e.v1.base.system.UserPageRpcResB+Z)vgo/app/admin/api/v1/base_system/protobufb\x06proto3"

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_system_v1_system_proto_goTypes = []any{
	(*SystemLogPageRpcInvoke)(nil),    // 0: v1.base.system.SystemLogPageRpcInvoke
	(*SystemLogPageRpcRes)(nil),       // 1: v1.base.system.SystemLogPageRpcRes
	(*SystemLogGatewayRpcInvoke)(nil), // 2: v1.base.system.SystemLogGatewayRpcInvoke
	(*SystemLogGatewayRpcRes)(nil),    // 3: v1.base.system.SystemLogGatewayRpcRes
	(*DepartmentListRpcInvoke)(nil),   // 4: v1.base.system.DepartmentListRpcInvoke
	(*DepartmentListRpcRes)(nil),      // 5: v1.base.system.DepartmentListRpcRes
	(*DepartmentResultItem)(nil),      // 6: v1.base.system.DepartmentResultItem
	(*UserPageRpcInvoke)(nil),         // 7: v1.base.system.UserPageRpcInvoke
	(*UserPageRpcRes)(nil),            // 8: v1.base.system.UserPageRpcRes
	(*pbentity.PageRpcInvoke)(nil),    // 9: pbentity.PageRpcInvoke
	(*pbentity.Pagination)(nil),       // 10: pbentity.Pagination
	(*pbentity.BaseSysUser)(nil),      // 11: pbentity.BaseSysUser
}
var file_system_v1_system_proto_depIdxs = []int32{
	6,  // 0: v1.base.system.DepartmentListRpcRes.Items:type_name -> v1.base.system.DepartmentResultItem
	9,  // 1: v1.base.system.UserPageRpcInvoke.PageReq:type_name -> pbentity.PageRpcInvoke
	10, // 2: v1.base.system.UserPageRpcRes.Pagination:type_name -> pbentity.Pagination
	11, // 3: v1.base.system.UserPageRpcRes.List:type_name -> pbentity.BaseSysUser
	0,  // 4: v1.base.system.BaseSys.SystemLogPage:input_type -> v1.base.system.SystemLogPageRpcInvoke
	2,  // 5: v1.base.system.BaseSys.SystemLogGateway:input_type -> v1.base.system.SystemLogGatewayRpcInvoke
	4,  // 6: v1.base.system.BaseSys.DepartmentList:input_type -> v1.base.system.DepartmentListRpcInvoke
	7,  // 7: v1.base.system.BaseSys.UserPage:input_type -> v1.base.system.UserPageRpcInvoke
	1,  // 8: v1.base.system.BaseSys.SystemLogPage:output_type -> v1.base.system.SystemLogPageRpcRes
	3,  // 9: v1.base.system.BaseSys.SystemLogGateway:output_type -> v1.base.system.SystemLogGatewayRpcRes
	5,  // 10: v1.base.system.BaseSys.DepartmentList:output_type -> v1.base.system.DepartmentListRpcRes
	8,  // 11: v1.base.system.BaseSys.UserPage:output_type -> v1.base.system.UserPageRpcRes
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	file_system_v1_system_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
