// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: system/v1/system.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemLogPageRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogPageRpcInvoke) Reset() {
	*x = SystemLogPageRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogPageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogPageRpcInvoke) ProtoMessage() {}

func (x *SystemLogPageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogPageRpcInvoke.ProtoReflect.Descriptor instead.
func (*SystemLogPageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type SystemLogPageRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogPageRpcRes) Reset() {
	*x = SystemLogPageRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogPageRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogPageRpcRes) ProtoMessage() {}

func (x *SystemLogPageRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogPageRpcRes.ProtoReflect.Descriptor instead.
func (*SystemLogPageRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

type SystemLogGatewayRpcInvoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip
	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty" dc:"ip"`
	// action
	Action string `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty" dc:"action"`
	// 参数
	Params string `protobuf:"bytes,3,opt,name=Params,proto3" json:"Params,omitempty" dc:"参数"`
	// 租父ID
	TenantId *int64 `protobuf:"varint,4,opt,name=TenantId,proto3,oneof" json:"TenantId,omitempty" dc:"租父ID"`
	// 用户ID
	UserId *int64 `protobuf:"varint,5,opt,name=UserId,proto3,oneof" json:"UserId,omitempty" dc:"用户ID"`
	// 追踪ID
	TraceId       string `protobuf:"bytes,6,opt,name=TraceId,proto3" json:"TraceId,omitempty" dc:"追踪ID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogGatewayRpcInvoke) Reset() {
	*x = SystemLogGatewayRpcInvoke{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogGatewayRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogGatewayRpcInvoke) ProtoMessage() {}

func (x *SystemLogGatewayRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogGatewayRpcInvoke.ProtoReflect.Descriptor instead.
func (*SystemLogGatewayRpcInvoke) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *SystemLogGatewayRpcInvoke) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *SystemLogGatewayRpcInvoke) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SystemLogGatewayRpcInvoke) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SystemLogGatewayRpcInvoke) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SystemLogGatewayRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLogGatewayRpcRes) Reset() {
	*x = SystemLogGatewayRpcRes{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLogGatewayRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLogGatewayRpcRes) ProtoMessage() {}

func (x *SystemLogGatewayRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLogGatewayRpcRes.ProtoReflect.Descriptor instead.
func (*SystemLogGatewayRpcRes) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

var File_system_v1_system_proto protoreflect.FileDescriptor

var file_system_v1_system_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x67, 0x65, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f,
	0x6b, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x19, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x70,
	0x63, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x54, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x70, 0x63, 0x52, 0x65,
	0x73, 0x32, 0xce, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65, 0x53, 0x79, 0x73, 0x12, 0x5c, 0x0a,
	0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x67, 0x65, 0x12, 0x26,
	0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x67, 0x65, 0x52, 0x70, 0x63,
	0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x1a, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f,
	0x67, 0x50, 0x61, 0x67, 0x65, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x12, 0x65, 0x0a, 0x10, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12,
	0x29, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x1a, 0x26, 0x2e, 0x76, 0x31, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_v1_system_proto_goTypes = []any{
	(*SystemLogPageRpcInvoke)(nil),    // 0: v1.base.system.SystemLogPageRpcInvoke
	(*SystemLogPageRpcRes)(nil),       // 1: v1.base.system.SystemLogPageRpcRes
	(*SystemLogGatewayRpcInvoke)(nil), // 2: v1.base.system.SystemLogGatewayRpcInvoke
	(*SystemLogGatewayRpcRes)(nil),    // 3: v1.base.system.SystemLogGatewayRpcRes
}
var file_system_v1_system_proto_depIdxs = []int32{
	0, // 0: v1.base.system.BaseSys.SystemLogPage:input_type -> v1.base.system.SystemLogPageRpcInvoke
	2, // 1: v1.base.system.BaseSys.SystemLogGateway:input_type -> v1.base.system.SystemLogGatewayRpcInvoke
	1, // 2: v1.base.system.BaseSys.SystemLogPage:output_type -> v1.base.system.SystemLogPageRpcRes
	3, // 3: v1.base.system.BaseSys.SystemLogGateway:output_type -> v1.base.system.SystemLogGatewayRpcRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	file_system_v1_system_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
