// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: comm/v1/comm.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonUpdateInvoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 更新标识
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty" dc:"更新标识"`
	// 更新值
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty" dc:"更新值"`
	// 其他参数
	Other         string `protobuf:"bytes,3,opt,name=Other,proto3" json:"Other,omitempty" dc:"其他参数"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonUpdateInvoke) Reset() {
	*x = PersonUpdateInvoke{}
	mi := &file_comm_v1_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonUpdateInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonUpdateInvoke) ProtoMessage() {}

func (x *PersonUpdateInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonUpdateInvoke.ProtoReflect.Descriptor instead.
func (*PersonUpdateInvoke) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{0}
}

func (x *PersonUpdateInvoke) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PersonUpdateInvoke) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PersonUpdateInvoke) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

type PersonUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonUpdateRes) Reset() {
	*x = PersonUpdateRes{}
	mi := &file_comm_v1_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonUpdateRes) ProtoMessage() {}

func (x *PersonUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonUpdateRes.ProtoReflect.Descriptor instead.
func (*PersonUpdateRes) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{1}
}

type PermmenuRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermmenuRpcInvoke) Reset() {
	*x = PermmenuRpcInvoke{}
	mi := &file_comm_v1_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermmenuRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermmenuRpcInvoke) ProtoMessage() {}

func (x *PermmenuRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermmenuRpcInvoke.ProtoReflect.Descriptor instead.
func (*PermmenuRpcInvoke) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{2}
}

type PermmenuRpcRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限集合
	Perms []string `protobuf:"bytes,1,rep,name=Perms,proto3" json:"Perms,omitempty" dc:"权限集合"`
	// 菜单集合
	Menus         []*Menu `protobuf:"bytes,2,rep,name=Menus,proto3" json:"Menus,omitempty" dc:"菜单集合"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermmenuRpcRes) Reset() {
	*x = PermmenuRpcRes{}
	mi := &file_comm_v1_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermmenuRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermmenuRpcRes) ProtoMessage() {}

func (x *PermmenuRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermmenuRpcRes.ProtoReflect.Descriptor instead.
func (*PermmenuRpcRes) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{3}
}

func (x *PermmenuRpcRes) GetPerms() []string {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *PermmenuRpcRes) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type Menu struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CreateTime string                 `protobuf:"bytes,1,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime string                 `protobuf:"bytes,2,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	// 图标
	Icon string `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty" dc:"图标"`
	// 菜单ID
	Id int64 `protobuf:"varint,4,opt,name=Id,proto3" json:"Id,omitempty" dc:"菜单ID"`
	// 是否显示
	IsShow bool `protobuf:"varint,5,opt,name=IsShow,proto3" json:"IsShow,omitempty" dc:"是否显示"`
	// 是否缓存
	KeepAlive bool `protobuf:"varint,6,opt,name=KeepAlive,proto3" json:"KeepAlive,omitempty" dc:"是否缓存"`
	// 菜单名称
	Name string `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty" dc:"菜单名称"`
	// 排序
	OrderNum int64 `protobuf:"varint,8,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序"`
	// 父ID
	ParentId int64 `protobuf:"varint,9,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"父ID"`
	// 菜单权限
	Perms string `protobuf:"bytes,10,opt,name=Perms,proto3" json:"Perms,omitempty" dc:"菜单权限"`
	// 路由地址
	Router string `protobuf:"bytes,11,opt,name=Router,proto3" json:"Router,omitempty" dc:"路由地址"`
	// 租户ID
	TenantId int64 `protobuf:"varint,12,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`
	// 菜单类型
	Type int32 `protobuf:"varint,13,opt,name=Type,proto3" json:"Type,omitempty" dc:"菜单类型"`
	// 视图路径
	ViewPath      string `protobuf:"bytes,14,opt,name=ViewPath,proto3" json:"ViewPath,omitempty" dc:"视图路径"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_comm_v1_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{4}
}

func (x *Menu) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Menu) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *Menu) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetOrderNum() int64 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *Menu) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Menu) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *Menu) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *Menu) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Menu) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Menu) GetViewPath() string {
	if x != nil {
		return x.ViewPath
	}
	return ""
}

type PersonRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonRpcInvoke) Reset() {
	*x = PersonRpcInvoke{}
	mi := &file_comm_v1_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRpcInvoke) ProtoMessage() {}

func (x *PersonRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRpcInvoke.ProtoReflect.Descriptor instead.
func (*PersonRpcInvoke) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{5}
}

type PersonRpcRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"用户ID"`
	// 部门ID
	DepartmentId int64 `protobuf:"varint,2,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty" dc:"部门ID"`
	// 头像
	HeadImg string `protobuf:"bytes,3,opt,name=HeadImg,proto3" json:"HeadImg,omitempty" dc:"头像"`
	// 姓名
	Name string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty" dc:"姓名"`
	// 昵称
	NickName string `protobuf:"bytes,5,opt,name=NickName,proto3" json:"NickName,omitempty" dc:"昵称"`
	// 密码版本
	PasswordV int64 `protobuf:"varint,6,opt,name=PasswordV,proto3" json:"PasswordV,omitempty" dc:"密码版本"`
	// 电话
	Phone string `protobuf:"bytes,7,opt,name=Phone,proto3" json:"Phone,omitempty" dc:"电话"`
	// 备注
	Remark string `protobuf:"bytes,8,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注"`
	// 状态
	Status int32 `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态"`
	// 租户ID
	TenantId int64 `protobuf:"varint,10,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`
	// 用户名
	UserName   string `protobuf:"bytes,11,opt,name=UserName,proto3" json:"UserName,omitempty" dc:"用户名"`
	CreateTime int64  `protobuf:"varint,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// 邮箱
	Email         string `protobuf:"bytes,15,opt,name=Email,proto3" json:"Email,omitempty" dc:"邮箱"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonRpcRes) Reset() {
	*x = PersonRpcRes{}
	mi := &file_comm_v1_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRpcRes) ProtoMessage() {}

func (x *PersonRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRpcRes.ProtoReflect.Descriptor instead.
func (*PersonRpcRes) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{6}
}

func (x *PersonRpcRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonRpcRes) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *PersonRpcRes) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

func (x *PersonRpcRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonRpcRes) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PersonRpcRes) GetPasswordV() int64 {
	if x != nil {
		return x.PasswordV
	}
	return 0
}

func (x *PersonRpcRes) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonRpcRes) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PersonRpcRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PersonRpcRes) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *PersonRpcRes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PersonRpcRes) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PersonRpcRes) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *PersonRpcRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginOutRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginOutRpcInvoke) Reset() {
	*x = LoginOutRpcInvoke{}
	mi := &file_comm_v1_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOutRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOutRpcInvoke) ProtoMessage() {}

func (x *LoginOutRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOutRpcInvoke.ProtoReflect.Descriptor instead.
func (*LoginOutRpcInvoke) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{7}
}

type LoginOutRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginOutRes) Reset() {
	*x = LoginOutRes{}
	mi := &file_comm_v1_comm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOutRes) ProtoMessage() {}

func (x *LoginOutRes) ProtoReflect() protoreflect.Message {
	mi := &file_comm_v1_comm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOutRes.ProtoReflect.Descriptor instead.
func (*LoginOutRes) Descriptor() ([]byte, []int) {
	return file_comm_v1_comm_proto_rawDescGZIP(), []int{8}
}

var File_comm_v1_comm_proto protoreflect.FileDescriptor

const file_comm_v1_comm_proto_rawDesc = "" +
	"\n" +
	"\x12comm/v1/comm.proto\x12\fv1.base.comm\"R\n" +
	"\x12PersonUpdateInvoke\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x14\n" +
	"\x05Other\x18\x03 \x01(\tR\x05Other\"\x11\n" +
	"\x0fPersonUpdateRes\"\x13\n" +
	"\x11PermmenuRpcInvoke\"P\n" +
	"\x0ePermmenuRpcRes\x12\x14\n" +
	"\x05Perms\x18\x01 \x03(\tR\x05Perms\x12(\n" +
	"\x05Menus\x18\x02 \x03(\v2\x12.v1.base.comm.MenuR\x05Menus\"\xe6\x02\n" +
	"\x04Menu\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x01 \x01(\tR\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x02 \x01(\tR\n" +
	"UpdateTime\x12\x12\n" +
	"\x04Icon\x18\x03 \x01(\tR\x04Icon\x12\x0e\n" +
	"\x02Id\x18\x04 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06IsShow\x18\x05 \x01(\bR\x06IsShow\x12\x1c\n" +
	"\tKeepAlive\x18\x06 \x01(\bR\tKeepAlive\x12\x12\n" +
	"\x04Name\x18\a \x01(\tR\x04Name\x12\x1a\n" +
	"\bOrderNum\x18\b \x01(\x03R\bOrderNum\x12\x1a\n" +
	"\bParentId\x18\t \x01(\x03R\bParentId\x12\x14\n" +
	"\x05Perms\x18\n" +
	" \x01(\tR\x05Perms\x12\x16\n" +
	"\x06Router\x18\v \x01(\tR\x06Router\x12\x1a\n" +
	"\bTenantId\x18\f \x01(\x03R\bTenantId\x12\x12\n" +
	"\x04Type\x18\r \x01(\x05R\x04Type\x12\x1a\n" +
	"\bViewPath\x18\x0e \x01(\tR\bViewPath\"\x11\n" +
	"\x0fPersonRpcInvoke\"\xfe\x02\n" +
	"\fPersonRpcRes\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\"\n" +
	"\fDepartmentId\x18\x02 \x01(\x03R\fDepartmentId\x12\x18\n" +
	"\aHeadImg\x18\x03 \x01(\tR\aHeadImg\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x1a\n" +
	"\bNickName\x18\x05 \x01(\tR\bNickName\x12\x1c\n" +
	"\tPasswordV\x18\x06 \x01(\x03R\tPasswordV\x12\x14\n" +
	"\x05Phone\x18\a \x01(\tR\x05Phone\x12\x16\n" +
	"\x06Remark\x18\b \x01(\tR\x06Remark\x12\x16\n" +
	"\x06Status\x18\t \x01(\x05R\x06Status\x12\x1a\n" +
	"\bTenantId\x18\n" +
	" \x01(\x03R\bTenantId\x12\x1a\n" +
	"\bUserName\x18\v \x01(\tR\bUserName\x12\x1e\n" +
	"\n" +
	"createTime\x18\f \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x0e \x01(\x03R\n" +
	"updateTime\x12\x14\n" +
	"\x05Email\x18\x0f \x01(\tR\x05Email\"\x13\n" +
	"\x11LoginOutRpcInvoke\"\r\n" +
	"\vLoginOutRes2\xb3\x02\n" +
	"\bBaseComm\x12I\n" +
	"\bPermmenu\x12\x1f.v1.base.comm.PermmenuRpcInvoke\x1a\x1c.v1.base.comm.PermmenuRpcRes\x12C\n" +
	"\x06Person\x12\x1d.v1.base.comm.PersonRpcInvoke\x1a\x1a.v1.base.comm.PersonRpcRes\x12F\n" +
	"\bLoginOut\x12\x1f.v1.base.comm.LoginOutRpcInvoke\x1a\x19.v1.base.comm.LoginOutRes\x12O\n" +
	"\fPersonUpdate\x12 .v1.base.comm.PersonUpdateInvoke\x1a\x1d.v1.base.comm.PersonUpdateResB>Z<github.com/vera-byte/vgo/app/admin/api/v1/base_comm/protobufb\x06proto3"

var (
	file_comm_v1_comm_proto_rawDescOnce sync.Once
	file_comm_v1_comm_proto_rawDescData []byte
)

func file_comm_v1_comm_proto_rawDescGZIP() []byte {
	file_comm_v1_comm_proto_rawDescOnce.Do(func() {
		file_comm_v1_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comm_v1_comm_proto_rawDesc), len(file_comm_v1_comm_proto_rawDesc)))
	})
	return file_comm_v1_comm_proto_rawDescData
}

var file_comm_v1_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comm_v1_comm_proto_goTypes = []any{
	(*PersonUpdateInvoke)(nil), // 0: v1.base.comm.PersonUpdateInvoke
	(*PersonUpdateRes)(nil),    // 1: v1.base.comm.PersonUpdateRes
	(*PermmenuRpcInvoke)(nil),  // 2: v1.base.comm.PermmenuRpcInvoke
	(*PermmenuRpcRes)(nil),     // 3: v1.base.comm.PermmenuRpcRes
	(*Menu)(nil),               // 4: v1.base.comm.Menu
	(*PersonRpcInvoke)(nil),    // 5: v1.base.comm.PersonRpcInvoke
	(*PersonRpcRes)(nil),       // 6: v1.base.comm.PersonRpcRes
	(*LoginOutRpcInvoke)(nil),  // 7: v1.base.comm.LoginOutRpcInvoke
	(*LoginOutRes)(nil),        // 8: v1.base.comm.LoginOutRes
}
var file_comm_v1_comm_proto_depIdxs = []int32{
	4, // 0: v1.base.comm.PermmenuRpcRes.Menus:type_name -> v1.base.comm.Menu
	2, // 1: v1.base.comm.BaseComm.Permmenu:input_type -> v1.base.comm.PermmenuRpcInvoke
	5, // 2: v1.base.comm.BaseComm.Person:input_type -> v1.base.comm.PersonRpcInvoke
	7, // 3: v1.base.comm.BaseComm.LoginOut:input_type -> v1.base.comm.LoginOutRpcInvoke
	0, // 4: v1.base.comm.BaseComm.PersonUpdate:input_type -> v1.base.comm.PersonUpdateInvoke
	3, // 5: v1.base.comm.BaseComm.Permmenu:output_type -> v1.base.comm.PermmenuRpcRes
	6, // 6: v1.base.comm.BaseComm.Person:output_type -> v1.base.comm.PersonRpcRes
	8, // 7: v1.base.comm.BaseComm.LoginOut:output_type -> v1.base.comm.LoginOutRes
	1, // 8: v1.base.comm.BaseComm.PersonUpdate:output_type -> v1.base.comm.PersonUpdateRes
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_comm_v1_comm_proto_init() }
func file_comm_v1_comm_proto_init() {
	if File_comm_v1_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comm_v1_comm_proto_rawDesc), len(file_comm_v1_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comm_v1_comm_proto_goTypes,
		DependencyIndexes: file_comm_v1_comm_proto_depIdxs,
		MessageInfos:      file_comm_v1_comm_proto_msgTypes,
	}.Build()
	File_comm_v1_comm_proto = out.File
	file_comm_v1_comm_proto_goTypes = nil
	file_comm_v1_comm_proto_depIdxs = nil
}
