// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pbentity/base_sys_department.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysDepartment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                  // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间"` // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间"` // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`    // 租户ID
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty" dc:"部门名称"`             // 部门名称
	ParentId      int32                  `protobuf:"varint,6,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"上级部门ID"`  // 上级部门ID
	OrderNum      int32                  `protobuf:"varint,7,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序"`      // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartment) Reset() {
	*x = BaseSysDepartment{}
	mi := &file_pbentity_base_sys_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartment) ProtoMessage() {}

func (x *BaseSysDepartment) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_base_sys_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartment.ProtoReflect.Descriptor instead.
func (*BaseSysDepartment) Descriptor() ([]byte, []int) {
	return file_pbentity_base_sys_department_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysDepartment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysDepartment) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysDepartment) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysDepartment) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysDepartment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysDepartment) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *BaseSysDepartment) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

var File_pbentity_base_sys_department_proto protoreflect.FileDescriptor

const file_pbentity_base_sys_department_proto_rawDesc = "" +
	"\n" +
	"\"pbentity/base_sys_department.proto\x12\bpbentity\"\xcb\x01\n" +
	"\x11BaseSysDepartment\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x02 \x01(\tR\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x03 \x01(\tR\n" +
	"UpdateTime\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12\x1a\n" +
	"\bParentId\x18\x06 \x01(\x05R\bParentId\x12\x1a\n" +
	"\bOrderNum\x18\a \x01(\x05R\bOrderNumB1Z/github.com/vera-byte/vgo/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_base_sys_department_proto_rawDescOnce sync.Once
	file_pbentity_base_sys_department_proto_rawDescData []byte
)

func file_pbentity_base_sys_department_proto_rawDescGZIP() []byte {
	file_pbentity_base_sys_department_proto_rawDescOnce.Do(func() {
		file_pbentity_base_sys_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_department_proto_rawDesc), len(file_pbentity_base_sys_department_proto_rawDesc)))
	})
	return file_pbentity_base_sys_department_proto_rawDescData
}

var file_pbentity_base_sys_department_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_base_sys_department_proto_goTypes = []any{
	(*BaseSysDepartment)(nil), // 0: pbentity.BaseSysDepartment
}
var file_pbentity_base_sys_department_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_base_sys_department_proto_init() }
func file_pbentity_base_sys_department_proto_init() {
	if File_pbentity_base_sys_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_department_proto_rawDesc), len(file_pbentity_base_sys_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_base_sys_department_proto_goTypes,
		DependencyIndexes: file_pbentity_base_sys_department_proto_depIdxs,
		MessageInfos:      file_pbentity_base_sys_department_proto_msgTypes,
	}.Build()
	File_pbentity_base_sys_department_proto = out.File
	file_pbentity_base_sys_department_proto_goTypes = nil
	file_pbentity_base_sys_department_proto_depIdxs = nil
}
