// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: pbentity/base_sys_user.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                                      // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间"`                     // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间"`                     // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`                        // 租户ID
	DepartmentId  int32                  `protobuf:"varint,5,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty" dc:"部门ID"`                // 部门ID
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"姓名"`                                   // 姓名
	Username      string                 `protobuf:"bytes,7,opt,name=Username,proto3" json:"Username,omitempty" dc:"用户名"`                          // 用户名
	Password      string                 `protobuf:"bytes,8,opt,name=Password,proto3" json:"Password,omitempty" dc:"密码"`                           // 密码
	PasswordV     int32                  `protobuf:"varint,9,opt,name=PasswordV,proto3" json:"PasswordV,omitempty" dc:"密码版本, 作用是改完密码，让原来的token失效"` // 密码版本, 作用是改完密码，让原来的token失效
	NickName      string                 `protobuf:"bytes,10,opt,name=NickName,proto3" json:"NickName,omitempty" dc:"昵称"`                          // 昵称
	HeadImg       string                 `protobuf:"bytes,11,opt,name=HeadImg,proto3" json:"HeadImg,omitempty" dc:"头像"`                            // 头像
	Phone         string                 `protobuf:"bytes,12,opt,name=Phone,proto3" json:"Phone,omitempty" dc:"手机"`                                // 手机
	Email         string                 `protobuf:"bytes,13,opt,name=Email,proto3" json:"Email,omitempty" dc:"邮箱"`                                // 邮箱
	Remark        string                 `protobuf:"bytes,14,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注"`                              // 备注
	Status        int32                  `protobuf:"varint,15,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态 0-禁用 1-启用"`                   // 状态 0-禁用 1-启用
	SocketId      string                 `protobuf:"bytes,16,opt,name=SocketId,proto3" json:"SocketId,omitempty" dc:"socketId"`                    // socketId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysUser) Reset() {
	*x = BaseSysUser{}
	mi := &file_pbentity_base_sys_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysUser) ProtoMessage() {}

func (x *BaseSysUser) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_base_sys_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysUser.ProtoReflect.Descriptor instead.
func (*BaseSysUser) Descriptor() ([]byte, []int) {
	return file_pbentity_base_sys_user_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysUser) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysUser) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysUser) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysUser) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *BaseSysUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BaseSysUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BaseSysUser) GetPasswordV() int32 {
	if x != nil {
		return x.PasswordV
	}
	return 0
}

func (x *BaseSysUser) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BaseSysUser) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

func (x *BaseSysUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BaseSysUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BaseSysUser) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BaseSysUser) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BaseSysUser) GetSocketId() string {
	if x != nil {
		return x.SocketId
	}
	return ""
}

var File_pbentity_base_sys_user_proto protoreflect.FileDescriptor

var file_pbentity_base_sys_user_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x73, 0x79, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xb5, 0x03, 0x0a, 0x0b, 0x42, 0x61, 0x73,
	0x65, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x56, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x56, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x42, 0x1c, 0x5a, 0x1a, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pbentity_base_sys_user_proto_rawDescOnce sync.Once
	file_pbentity_base_sys_user_proto_rawDescData []byte
)

func file_pbentity_base_sys_user_proto_rawDescGZIP() []byte {
	file_pbentity_base_sys_user_proto_rawDescOnce.Do(func() {
		file_pbentity_base_sys_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_user_proto_rawDesc), len(file_pbentity_base_sys_user_proto_rawDesc)))
	})
	return file_pbentity_base_sys_user_proto_rawDescData
}

var file_pbentity_base_sys_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_base_sys_user_proto_goTypes = []any{
	(*BaseSysUser)(nil), // 0: pbentity.BaseSysUser
}
var file_pbentity_base_sys_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_base_sys_user_proto_init() }
func file_pbentity_base_sys_user_proto_init() {
	if File_pbentity_base_sys_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_user_proto_rawDesc), len(file_pbentity_base_sys_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_base_sys_user_proto_goTypes,
		DependencyIndexes: file_pbentity_base_sys_user_proto_depIdxs,
		MessageInfos:      file_pbentity_base_sys_user_proto_msgTypes,
	}.Build()
	File_pbentity_base_sys_user_proto = out.File
	file_pbentity_base_sys_user_proto_goTypes = nil
	file_pbentity_base_sys_user_proto_depIdxs = nil
}
