// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pbentity/base_sys_menu.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                    // ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dc:"创建时间"`     // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" dc:"更新时间"`     // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`      // 租户ID
	ParentId      int32                  `protobuf:"varint,5,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"父菜单ID"`     // 父菜单ID
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"菜单名称"`               // 菜单名称
	Router        string                 `protobuf:"bytes,7,opt,name=Router,proto3" json:"Router,omitempty" dc:"菜单地址"`           // 菜单地址
	Perms         string                 `protobuf:"bytes,8,opt,name=Perms,proto3" json:"Perms,omitempty" dc:"权限标识"`             // 权限标识
	Type          int32                  `protobuf:"varint,9,opt,name=Type,proto3" json:"Type,omitempty" dc:"类型 0-目录 1-菜单 2-按钮"` // 类型 0-目录 1-菜单 2-按钮
	Icon          string                 `protobuf:"bytes,10,opt,name=Icon,proto3" json:"Icon,omitempty" dc:"图标"`                // 图标
	OrderNum      int32                  `protobuf:"varint,11,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序"`       // 排序
	ViewPath      string                 `protobuf:"bytes,12,opt,name=ViewPath,proto3" json:"ViewPath,omitempty" dc:"视图地址"`      // 视图地址
	KeepAlive     bool                   `protobuf:"varint,13,opt,name=KeepAlive,proto3" json:"KeepAlive,omitempty" dc:"路由缓存"`   // 路由缓存
	IsShow        bool                   `protobuf:"varint,14,opt,name=IsShow,proto3" json:"IsShow,omitempty" dc:"是否显示"`         // 是否显示
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"软删除时间"`   // 软删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysMenu) Reset() {
	*x = BaseSysMenu{}
	mi := &file_pbentity_base_sys_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysMenu) ProtoMessage() {}

func (x *BaseSysMenu) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_base_sys_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysMenu.ProtoReflect.Descriptor instead.
func (*BaseSysMenu) Descriptor() ([]byte, []int) {
	return file_pbentity_base_sys_menu_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysMenu) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysMenu) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseSysMenu) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BaseSysMenu) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysMenu) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *BaseSysMenu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysMenu) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *BaseSysMenu) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *BaseSysMenu) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BaseSysMenu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *BaseSysMenu) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *BaseSysMenu) GetViewPath() string {
	if x != nil {
		return x.ViewPath
	}
	return ""
}

func (x *BaseSysMenu) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *BaseSysMenu) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *BaseSysMenu) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_base_sys_menu_proto protoreflect.FileDescriptor

const file_pbentity_base_sys_menu_proto_rawDesc = "" +
	"\n" +
	"\x1cpbentity/base_sys_menu.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x03\n" +
	"\vBaseSysMenu\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\x1a\n" +
	"\bParentId\x18\x05 \x01(\x05R\bParentId\x12\x12\n" +
	"\x04Name\x18\x06 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Router\x18\a \x01(\tR\x06Router\x12\x14\n" +
	"\x05Perms\x18\b \x01(\tR\x05Perms\x12\x12\n" +
	"\x04Type\x18\t \x01(\x05R\x04Type\x12\x12\n" +
	"\x04Icon\x18\n" +
	" \x01(\tR\x04Icon\x12\x1a\n" +
	"\bOrderNum\x18\v \x01(\x05R\bOrderNum\x12\x1a\n" +
	"\bViewPath\x18\f \x01(\tR\bViewPath\x12\x1c\n" +
	"\tKeepAlive\x18\r \x01(\bR\tKeepAlive\x12\x16\n" +
	"\x06IsShow\x18\x0e \x01(\bR\x06IsShow\x128\n" +
	"\tDeletedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB1Z/github.com/vera-byte/vgo/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_base_sys_menu_proto_rawDescOnce sync.Once
	file_pbentity_base_sys_menu_proto_rawDescData []byte
)

func file_pbentity_base_sys_menu_proto_rawDescGZIP() []byte {
	file_pbentity_base_sys_menu_proto_rawDescOnce.Do(func() {
		file_pbentity_base_sys_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_menu_proto_rawDesc), len(file_pbentity_base_sys_menu_proto_rawDesc)))
	})
	return file_pbentity_base_sys_menu_proto_rawDescData
}

var file_pbentity_base_sys_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_base_sys_menu_proto_goTypes = []any{
	(*BaseSysMenu)(nil),           // 0: pbentity.BaseSysMenu
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_base_sys_menu_proto_depIdxs = []int32{
	1, // 0: pbentity.BaseSysMenu.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.BaseSysMenu.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.BaseSysMenu.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_base_sys_menu_proto_init() }
func file_pbentity_base_sys_menu_proto_init() {
	if File_pbentity_base_sys_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_menu_proto_rawDesc), len(file_pbentity_base_sys_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_base_sys_menu_proto_goTypes,
		DependencyIndexes: file_pbentity_base_sys_menu_proto_depIdxs,
		MessageInfos:      file_pbentity_base_sys_menu_proto_msgTypes,
	}.Build()
	File_pbentity_base_sys_menu_proto = out.File
	file_pbentity_base_sys_menu_proto_goTypes = nil
	file_pbentity_base_sys_menu_proto_depIdxs = nil
}
