// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pbentity/base_sys_user.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                                      // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间"`                     // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间"`                     // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`                        // 租户ID
	DepartmentId  int32                  `protobuf:"varint,5,opt,name=DepartmentId,proto3" json:"DepartmentId,omitempty" dc:"部门ID"`                // 部门ID
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"姓名"`                                   // 姓名
	Username      string                 `protobuf:"bytes,7,opt,name=Username,proto3" json:"Username,omitempty" dc:"用户名"`                          // 用户名
	Password      string                 `protobuf:"bytes,8,opt,name=Password,proto3" json:"Password,omitempty" dc:"密码"`                           // 密码
	PasswordV     int32                  `protobuf:"varint,9,opt,name=PasswordV,proto3" json:"PasswordV,omitempty" dc:"密码版本, 作用是改完密码，让原来的token失效"` // 密码版本, 作用是改完密码，让原来的token失效
	NickName      string                 `protobuf:"bytes,10,opt,name=NickName,proto3" json:"NickName,omitempty" dc:"昵称"`                          // 昵称
	HeadImg       string                 `protobuf:"bytes,11,opt,name=HeadImg,proto3" json:"HeadImg,omitempty" dc:"头像"`                            // 头像
	Phone         string                 `protobuf:"bytes,12,opt,name=Phone,proto3" json:"Phone,omitempty" dc:"手机"`                                // 手机
	Email         string                 `protobuf:"bytes,13,opt,name=Email,proto3" json:"Email,omitempty" dc:"邮箱"`                                // 邮箱
	Remark        string                 `protobuf:"bytes,14,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注"`                              // 备注
	Status        int32                  `protobuf:"varint,15,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态 0-禁用 1-启用"`                   // 状态 0-禁用 1-启用
	SocketId      string                 `protobuf:"bytes,16,opt,name=SocketId,proto3" json:"SocketId,omitempty" dc:"socketId"`                    // socketId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysUser) Reset() {
	*x = BaseSysUser{}
	mi := &file_pbentity_base_sys_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysUser) ProtoMessage() {}

func (x *BaseSysUser) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_base_sys_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysUser.ProtoReflect.Descriptor instead.
func (*BaseSysUser) Descriptor() ([]byte, []int) {
	return file_pbentity_base_sys_user_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysUser) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysUser) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysUser) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysUser) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *BaseSysUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BaseSysUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BaseSysUser) GetPasswordV() int32 {
	if x != nil {
		return x.PasswordV
	}
	return 0
}

func (x *BaseSysUser) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BaseSysUser) GetHeadImg() string {
	if x != nil {
		return x.HeadImg
	}
	return ""
}

func (x *BaseSysUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BaseSysUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BaseSysUser) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BaseSysUser) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BaseSysUser) GetSocketId() string {
	if x != nil {
		return x.SocketId
	}
	return ""
}

var File_pbentity_base_sys_user_proto protoreflect.FileDescriptor

const file_pbentity_base_sys_user_proto_rawDesc = "" +
	"\n" +
	"\x1cpbentity/base_sys_user.proto\x12\bpbentity\"\xb5\x03\n" +
	"\vBaseSysUser\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x02 \x01(\tR\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x03 \x01(\tR\n" +
	"UpdateTime\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\"\n" +
	"\fDepartmentId\x18\x05 \x01(\x05R\fDepartmentId\x12\x12\n" +
	"\x04Name\x18\x06 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUsername\x18\a \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\b \x01(\tR\bPassword\x12\x1c\n" +
	"\tPasswordV\x18\t \x01(\x05R\tPasswordV\x12\x1a\n" +
	"\bNickName\x18\n" +
	" \x01(\tR\bNickName\x12\x18\n" +
	"\aHeadImg\x18\v \x01(\tR\aHeadImg\x12\x14\n" +
	"\x05Phone\x18\f \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\r \x01(\tR\x05Email\x12\x16\n" +
	"\x06Remark\x18\x0e \x01(\tR\x06Remark\x12\x16\n" +
	"\x06Status\x18\x0f \x01(\x05R\x06Status\x12\x1a\n" +
	"\bSocketId\x18\x10 \x01(\tR\bSocketIdB1Z/github.com/vera-byte/vgo/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_base_sys_user_proto_rawDescOnce sync.Once
	file_pbentity_base_sys_user_proto_rawDescData []byte
)

func file_pbentity_base_sys_user_proto_rawDescGZIP() []byte {
	file_pbentity_base_sys_user_proto_rawDescOnce.Do(func() {
		file_pbentity_base_sys_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_user_proto_rawDesc), len(file_pbentity_base_sys_user_proto_rawDesc)))
	})
	return file_pbentity_base_sys_user_proto_rawDescData
}

var file_pbentity_base_sys_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_base_sys_user_proto_goTypes = []any{
	(*BaseSysUser)(nil), // 0: pbentity.BaseSysUser
}
var file_pbentity_base_sys_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_base_sys_user_proto_init() }
func file_pbentity_base_sys_user_proto_init() {
	if File_pbentity_base_sys_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_user_proto_rawDesc), len(file_pbentity_base_sys_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_base_sys_user_proto_goTypes,
		DependencyIndexes: file_pbentity_base_sys_user_proto_depIdxs,
		MessageInfos:      file_pbentity_base_sys_user_proto_msgTypes,
	}.Build()
	File_pbentity_base_sys_user_proto = out.File
	file_pbentity_base_sys_user_proto_goTypes = nil
	file_pbentity_base_sys_user_proto_depIdxs = nil
}
