// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pbentity/base_sys_role_menu.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysRoleMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                 // ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dc:"创建时间"`  // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" dc:"更新时间"`  // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`   // 租户ID
	RoleId        int32                  `protobuf:"varint,5,opt,name=RoleId,proto3" json:"RoleId,omitempty" dc:"角色ID"`       // 角色ID
	MenuId        int32                  `protobuf:"varint,6,opt,name=MenuId,proto3" json:"MenuId,omitempty" dc:"菜单ID"`       // 菜单ID
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"软删除时间"` // 软删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysRoleMenu) Reset() {
	*x = BaseSysRoleMenu{}
	mi := &file_pbentity_base_sys_role_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysRoleMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysRoleMenu) ProtoMessage() {}

func (x *BaseSysRoleMenu) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_base_sys_role_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysRoleMenu.ProtoReflect.Descriptor instead.
func (*BaseSysRoleMenu) Descriptor() ([]byte, []int) {
	return file_pbentity_base_sys_role_menu_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysRoleMenu) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysRoleMenu) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseSysRoleMenu) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BaseSysRoleMenu) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysRoleMenu) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BaseSysRoleMenu) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *BaseSysRoleMenu) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_base_sys_role_menu_proto protoreflect.FileDescriptor

const file_pbentity_base_sys_role_menu_proto_rawDesc = "" +
	"\n" +
	"!pbentity/base_sys_role_menu.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\x0fBaseSysRoleMenu\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\x16\n" +
	"\x06RoleId\x18\x05 \x01(\x05R\x06RoleId\x12\x16\n" +
	"\x06MenuId\x18\x06 \x01(\x05R\x06MenuId\x128\n" +
	"\tDeletedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB1Z/github.com/vera-byte/vgo/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_base_sys_role_menu_proto_rawDescOnce sync.Once
	file_pbentity_base_sys_role_menu_proto_rawDescData []byte
)

func file_pbentity_base_sys_role_menu_proto_rawDescGZIP() []byte {
	file_pbentity_base_sys_role_menu_proto_rawDescOnce.Do(func() {
		file_pbentity_base_sys_role_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_role_menu_proto_rawDesc), len(file_pbentity_base_sys_role_menu_proto_rawDesc)))
	})
	return file_pbentity_base_sys_role_menu_proto_rawDescData
}

var file_pbentity_base_sys_role_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_base_sys_role_menu_proto_goTypes = []any{
	(*BaseSysRoleMenu)(nil),       // 0: pbentity.BaseSysRoleMenu
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_base_sys_role_menu_proto_depIdxs = []int32{
	1, // 0: pbentity.BaseSysRoleMenu.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.BaseSysRoleMenu.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.BaseSysRoleMenu.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_base_sys_role_menu_proto_init() }
func file_pbentity_base_sys_role_menu_proto_init() {
	if File_pbentity_base_sys_role_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_base_sys_role_menu_proto_rawDesc), len(file_pbentity_base_sys_role_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_base_sys_role_menu_proto_goTypes,
		DependencyIndexes: file_pbentity_base_sys_role_menu_proto_depIdxs,
		MessageInfos:      file_pbentity_base_sys_role_menu_proto_msgTypes,
	}.Build()
	File_pbentity_base_sys_role_menu_proto = out.File
	file_pbentity_base_sys_role_menu_proto_goTypes = nil
	file_pbentity_base_sys_role_menu_proto_depIdxs = nil
}
