// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pbentity/page.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRpcInvoke) Reset() {
	*x = PageRpcInvoke{}
	mi := &file_pbentity_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRpcInvoke) ProtoMessage() {}

func (x *PageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRpcInvoke.ProtoReflect.Descriptor instead.
func (*PageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_pbentity_page_proto_rawDescGZIP(), []int{0}
}

func (x *PageRpcInvoke) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRpcInvoke) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageRpcInvoke) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *PageRpcInvoke) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pbentity_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pbentity_page_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pbentity_page_proto protoreflect.FileDescriptor

const file_pbentity_page_proto_rawDesc = "" +
	"\n" +
	"\x13pbentity/page.proto\x12\bpbentity\"a\n" +
	"\rPageRpcInvoke\x12\x12\n" +
	"\x04Page\x18\x01 \x01(\x05R\x04Page\x12\x12\n" +
	"\x04Size\x18\x02 \x01(\x05R\x04Size\x12\x12\n" +
	"\x04Sort\x18\x03 \x01(\tR\x04Sort\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\"J\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04Page\x18\x01 \x01(\x05R\x04Page\x12\x12\n" +
	"\x04Size\x18\x02 \x01(\x05R\x04Size\x12\x14\n" +
	"\x05Total\x18\x03 \x01(\x03R\x05TotalB1Z/github.com/vera-byte/vgo/app/admin/api/pbentityb\x06proto3"

var (
	file_pbentity_page_proto_rawDescOnce sync.Once
	file_pbentity_page_proto_rawDescData []byte
)

func file_pbentity_page_proto_rawDescGZIP() []byte {
	file_pbentity_page_proto_rawDescOnce.Do(func() {
		file_pbentity_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_page_proto_rawDesc), len(file_pbentity_page_proto_rawDesc)))
	})
	return file_pbentity_page_proto_rawDescData
}

var file_pbentity_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbentity_page_proto_goTypes = []any{
	(*PageRpcInvoke)(nil), // 0: pbentity.PageRpcInvoke
	(*Pagination)(nil),    // 1: pbentity.Pagination
}
var file_pbentity_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_page_proto_init() }
func file_pbentity_page_proto_init() {
	if File_pbentity_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_page_proto_rawDesc), len(file_pbentity_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_page_proto_goTypes,
		DependencyIndexes: file_pbentity_page_proto_depIdxs,
		MessageInfos:      file_pbentity_page_proto_msgTypes,
	}.Build()
	File_pbentity_page_proto = out.File
	file_pbentity_page_proto_goTypes = nil
	file_pbentity_page_proto_depIdxs = nil
}
