// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: protobuf/pbentity/base_sys_param.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID"`                                 // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间"`                // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间"`                // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID"`         // 租户ID
	KeyName       string                 `protobuf:"bytes,5,opt,name=KeyName,proto3" json:"KeyName,omitempty" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键" dc:"键"`                                   // 键
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称"`                              // 名称
	Data          string                 `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据" dc:"数据"`                              // 数据
	DataType      int32                  `protobuf:"varint,8,opt,name=DataType,proto3" json:"DataType,omitempty" dc:"数据类型 0-字符串 1-富文本 2-文件" dc:"数据类型 0-字符串 1-富文本 2-文件" dc:"数据类型 0-字符串 1-富文本 2-文件" dc:"数据类型 0-字符串 1-富文本 2-文件"` // 数据类型 0-字符串 1-富文本 2-文件
	Remark        string                 `protobuf:"bytes,9,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注"`                          // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysParam) Reset() {
	*x = BaseSysParam{}
	mi := &file_protobuf_pbentity_base_sys_param_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysParam) ProtoMessage() {}

func (x *BaseSysParam) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pbentity_base_sys_param_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysParam.ProtoReflect.Descriptor instead.
func (*BaseSysParam) Descriptor() ([]byte, []int) {
	return file_protobuf_pbentity_base_sys_param_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysParam) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysParam) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysParam) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysParam) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysParam) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *BaseSysParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysParam) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BaseSysParam) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *BaseSysParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_protobuf_pbentity_base_sys_param_proto protoreflect.FileDescriptor

var file_protobuf_pbentity_base_sys_param_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x22, 0xf0, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x53, 0x79, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x42, 0x1c, 0x5a, 0x1a, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_pbentity_base_sys_param_proto_rawDescOnce sync.Once
	file_protobuf_pbentity_base_sys_param_proto_rawDescData []byte
)

func file_protobuf_pbentity_base_sys_param_proto_rawDescGZIP() []byte {
	file_protobuf_pbentity_base_sys_param_proto_rawDescOnce.Do(func() {
		file_protobuf_pbentity_base_sys_param_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_pbentity_base_sys_param_proto_rawDesc), len(file_protobuf_pbentity_base_sys_param_proto_rawDesc)))
	})
	return file_protobuf_pbentity_base_sys_param_proto_rawDescData
}

var file_protobuf_pbentity_base_sys_param_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_pbentity_base_sys_param_proto_goTypes = []any{
	(*BaseSysParam)(nil), // 0: pbentity.BaseSysParam
}
var file_protobuf_pbentity_base_sys_param_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_pbentity_base_sys_param_proto_init() }
func file_protobuf_pbentity_base_sys_param_proto_init() {
	if File_protobuf_pbentity_base_sys_param_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_pbentity_base_sys_param_proto_rawDesc), len(file_protobuf_pbentity_base_sys_param_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_pbentity_base_sys_param_proto_goTypes,
		DependencyIndexes: file_protobuf_pbentity_base_sys_param_proto_depIdxs,
		MessageInfos:      file_protobuf_pbentity_base_sys_param_proto_msgTypes,
	}.Build()
	File_protobuf_pbentity_base_sys_param_proto = out.File
	file_protobuf_pbentity_base_sys_param_proto_goTypes = nil
	file_protobuf_pbentity_base_sys_param_proto_depIdxs = nil
}
