// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: base/v1/base.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty" v:"required"` // v:required
	Widget        int32                  `protobuf:"varint,2,opt,name=Widget,proto3" json:"Widget,omitempty" v:"required"` // v:required
	Color         string                 `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color,omitempty" v:"required"`    // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaReq) Reset() {
	*x = CaptchaReq{}
	mi := &file_base_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaReq) ProtoMessage() {}

func (x *CaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaReq.ProtoReflect.Descriptor instead.
func (*CaptchaReq) Descriptor() ([]byte, []int) {
	return file_base_v1_base_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaReq) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaReq) GetWidget() int32 {
	if x != nil {
		return x.Widget
	}
	return 0
}

func (x *CaptchaReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type CaptchaRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=CaptchaId,proto3" json:"CaptchaId,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRes) Reset() {
	*x = CaptchaRes{}
	mi := &file_base_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRes) ProtoMessage() {}

func (x *CaptchaRes) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRes.ProtoReflect.Descriptor instead.
func (*CaptchaRes) Descriptor() ([]byte, []int) {
	return file_base_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaRes) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_base_v1_base_proto protoreflect.FileDescriptor

var file_base_v1_base_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x52, 0x0a,
	0x0a, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x32, 0x3b, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x12, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x73, 0x42, 0x24,
	0x5a, 0x22, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_base_v1_base_proto_rawDescOnce sync.Once
	file_base_v1_base_proto_rawDescData []byte
)

func file_base_v1_base_proto_rawDescGZIP() []byte {
	file_base_v1_base_proto_rawDescOnce.Do(func() {
		file_base_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_base_proto_rawDesc), len(file_base_v1_base_proto_rawDesc)))
	})
	return file_base_v1_base_proto_rawDescData
}

var file_base_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_v1_base_proto_goTypes = []any{
	(*CaptchaReq)(nil), // 0: base.v1.CaptchaReq
	(*CaptchaRes)(nil), // 1: base.v1.CaptchaRes
}
var file_base_v1_base_proto_depIdxs = []int32{
	0, // 0: base.v1.Base.Captcha:input_type -> base.v1.CaptchaReq
	1, // 1: base.v1.Base.Captcha:output_type -> base.v1.CaptchaRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_v1_base_proto_init() }
func file_base_v1_base_proto_init() {
	if File_base_v1_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_base_proto_rawDesc), len(file_base_v1_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_v1_base_proto_goTypes,
		DependencyIndexes: file_base_v1_base_proto_depIdxs,
		MessageInfos:      file_base_v1_base_proto_msgTypes,
	}.Build()
	File_base_v1_base_proto = out.File
	file_base_v1_base_proto_goTypes = nil
	file_base_v1_base_proto_depIdxs = nil
}
