// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: app/admin/manifest/protobuf/pbentity/base_sys_menu.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID"`                                // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间"`     // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间"`     // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID"`        // 租户ID
	ParentId      int32                  `protobuf:"varint,5,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID" dc:"父菜单ID"`         // 父菜单ID
	Name          string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称" dc:"菜单名称"`       // 菜单名称
	Router        string                 `protobuf:"bytes,7,opt,name=Router,proto3" json:"Router,omitempty" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址" dc:"菜单地址"`   // 菜单地址
	Perms         string                 `protobuf:"bytes,8,opt,name=Perms,proto3" json:"Perms,omitempty" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识" dc:"权限标识"`     // 权限标识
	Type          int32                  `protobuf:"varint,9,opt,name=Type,proto3" json:"Type,omitempty" dc:"类型 0-目录 1-菜单 2-按钮" dc:"类型 0-目录 1-菜单 2-按钮" dc:"类型 0-目录 1-菜单 2-按钮" dc:"类型 0-目录 1-菜单 2-按钮" dc:"类型 0-目录 1-菜单 2-按钮"` // 类型 0-目录 1-菜单 2-按钮
	Icon          string                 `protobuf:"bytes,10,opt,name=Icon,proto3" json:"Icon,omitempty" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标" dc:"图标"`                            // 图标
	OrderNum      int32                  `protobuf:"varint,11,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序"`                   // 排序
	ViewPath      string                 `protobuf:"bytes,12,opt,name=ViewPath,proto3" json:"ViewPath,omitempty" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址" dc:"视图地址"`        // 视图地址
	KeepAlive     int32                  `protobuf:"varint,13,opt,name=KeepAlive,proto3" json:"KeepAlive,omitempty" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存" dc:"路由缓存"`     // 路由缓存
	IsShow        int32                  `protobuf:"varint,14,opt,name=IsShow,proto3" json:"IsShow,omitempty" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示" dc:"是否显示"` // 是否显示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysMenu) Reset() {
	*x = BaseSysMenu{}
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysMenu) ProtoMessage() {}

func (x *BaseSysMenu) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysMenu.ProtoReflect.Descriptor instead.
func (*BaseSysMenu) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysMenu) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysMenu) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysMenu) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysMenu) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysMenu) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *BaseSysMenu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysMenu) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *BaseSysMenu) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *BaseSysMenu) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BaseSysMenu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *BaseSysMenu) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *BaseSysMenu) GetViewPath() string {
	if x != nil {
		return x.ViewPath
	}
	return ""
}

func (x *BaseSysMenu) GetKeepAlive() int32 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *BaseSysMenu) GetIsShow() int32 {
	if x != nil {
		return x.IsShow
	}
	return 0
}

var File_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto protoreflect.FileDescriptor

var file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDesc = string([]byte{
	0x0a, 0x38, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x5f,
	0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0xed, 0x02, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x53, 0x79, 0x73,
	0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x65, 0x72, 0x6d,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x69, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x49, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x73,
	0x53, 0x68, 0x6f, 0x77, 0x42, 0x1c, 0x5a, 0x1a, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescOnce sync.Once
	file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescData []byte
)

func file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescGZIP() []byte {
	file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescOnce.Do(func() {
		file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDesc)))
	})
	return file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDescData
}

var file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_goTypes = []any{
	(*BaseSysMenu)(nil), // 0: pbentity.BaseSysMenu
}
var file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_init() }
func file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_init() {
	if File_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_goTypes,
		DependencyIndexes: file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_depIdxs,
		MessageInfos:      file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_msgTypes,
	}.Build()
	File_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto = out.File
	file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_goTypes = nil
	file_app_admin_manifest_protobuf_pbentity_base_sys_menu_proto_depIdxs = nil
}
