// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: app/admin/manifest/protobuf/pbentity/base_sys_role.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysRole struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID"`                             // ID
	CreateTime       string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间"`  // 创建时间
	UpdateTime       string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间"`  // 更新时间
	TenantId         int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID"`     // 租户ID
	UserId           string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID" dc:"用户ID"`          // 用户ID
	Name             string                 `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称" dc:"名称"`                          // 名称
	Label            string                 `protobuf:"bytes,7,opt,name=Label,proto3" json:"Label,omitempty" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签" dc:"角色标签"`  // 角色标签
	Remark           string                 `protobuf:"bytes,8,opt,name=Remark,proto3" json:"Remark,omitempty" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注" dc:"备注"`                      // 备注
	Relevance        int32                  `protobuf:"varint,9,opt,name=Relevance,proto3" json:"Relevance,omitempty" dc:"数据权限是否关联上下级" dc:"数据权限是否关联上下级" dc:"数据权限是否关联上下级" dc:"数据权限是否关联上下级" dc:"数据权限是否关联上下级" dc:"数据权限是否关联上下级"` // 数据权限是否关联上下级
	MenuIdList       string                 `protobuf:"bytes,10,opt,name=MenuIdList,proto3" json:"MenuIdList,omitempty" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限" dc:"菜单权限"` // 菜单权限
	DepartmentIdList string                 `protobuf:"bytes,11,opt,name=DepartmentIdList,proto3" json:"DepartmentIdList,omitempty" dc:"部门权限" dc:"部门权限" dc:"部门权限" dc:"部门权限" dc:"部门权限" dc:"部门权限" dc:"部门权限" dc:"部门权限"`         // 部门权限
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BaseSysRole) Reset() {
	*x = BaseSysRole{}
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysRole) ProtoMessage() {}

func (x *BaseSysRole) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysRole.ProtoReflect.Descriptor instead.
func (*BaseSysRole) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysRole) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysRole) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysRole) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysRole) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseSysRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysRole) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BaseSysRole) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BaseSysRole) GetRelevance() int32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

func (x *BaseSysRole) GetMenuIdList() string {
	if x != nil {
		return x.MenuIdList
	}
	return ""
}

func (x *BaseSysRole) GetDepartmentIdList() string {
	if x != nil {
		return x.DepartmentIdList
	}
	return ""
}

var File_app_admin_manifest_protobuf_pbentity_base_sys_role_proto protoreflect.FileDescriptor

var file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDesc = string([]byte{
	0x0a, 0x38, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0xbd, 0x02, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x53, 0x79, 0x73,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x6c, 0x65, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52,
	0x65, 0x6c, 0x65, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x6e, 0x75,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescOnce sync.Once
	file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescData []byte
)

func file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescGZIP() []byte {
	file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescOnce.Do(func() {
		file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDesc)))
	})
	return file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDescData
}

var file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_goTypes = []any{
	(*BaseSysRole)(nil), // 0: pbentity.BaseSysRole
}
var file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_init() }
func file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_init() {
	if File_app_admin_manifest_protobuf_pbentity_base_sys_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_goTypes,
		DependencyIndexes: file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_depIdxs,
		MessageInfos:      file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_msgTypes,
	}.Build()
	File_app_admin_manifest_protobuf_pbentity_base_sys_role_proto = out.File
	file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_goTypes = nil
	file_app_admin_manifest_protobuf_pbentity_base_sys_role_proto_depIdxs = nil
}
