// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: app/admin/manifest/protobuf/pbentity/base_sys_department.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysDepartment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID" dc:"ID"`                 // ID
	CreateTime    string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间" dc:"创建时间"`        // 创建时间
	UpdateTime    string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间" dc:"更新时间"`        // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID" dc:"租户ID"` // 租户ID
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty" dc:"部门名称" dc:"部门名称" dc:"部门名称" dc:"部门名称" dc:"部门名称" dc:"部门名称"`          // 部门名称
	ParentId      int32                  `protobuf:"varint,6,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"上级部门ID" dc:"上级部门ID" dc:"上级部门ID" dc:"上级部门ID" dc:"上级部门ID"` // 上级部门ID
	OrderNum      int32                  `protobuf:"varint,7,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序" dc:"排序"`     // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartment) Reset() {
	*x = BaseSysDepartment{}
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartment) ProtoMessage() {}

func (x *BaseSysDepartment) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartment.ProtoReflect.Descriptor instead.
func (*BaseSysDepartment) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysDepartment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysDepartment) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseSysDepartment) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BaseSysDepartment) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysDepartment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysDepartment) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *BaseSysDepartment) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

var File_app_admin_manifest_protobuf_pbentity_base_sys_department_proto protoreflect.FileDescriptor

var file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDesc = string([]byte{
	0x0a, 0x3e, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x5f,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xcb, 0x01, 0x0a, 0x11, 0x42,
	0x61, 0x73, 0x65, 0x53, 0x79, 0x73, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x42, 0x1c, 0x5a, 0x1a, 0x76, 0x67, 0x6f, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescOnce sync.Once
	file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescData []byte
)

func file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescGZIP() []byte {
	file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescOnce.Do(func() {
		file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDesc)))
	})
	return file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDescData
}

var file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_goTypes = []any{
	(*BaseSysDepartment)(nil), // 0: pbentity.BaseSysDepartment
}
var file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_init() }
func file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_init() {
	if File_app_admin_manifest_protobuf_pbentity_base_sys_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDesc), len(file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_goTypes,
		DependencyIndexes: file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_depIdxs,
		MessageInfos:      file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_msgTypes,
	}.Build()
	File_app_admin_manifest_protobuf_pbentity_base_sys_department_proto = out.File
	file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_goTypes = nil
	file_app_admin_manifest_protobuf_pbentity_base_sys_department_proto_depIdxs = nil
}
