// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_open

import (
	"vgo/utility"

	v1 "github.com/vera-byte/vgo/app/admin/api/open/v1"
	"github.com/vera-byte/vgo/app/gateway/api/admin_open"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	AdminBaseOpenClient v1.BaseOpenClient
}

func NewV1() admin_open.IAdminOpenV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("admin", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
	return &ControllerV1{
		AdminBaseOpenClient: v1.NewBaseOpenClient(conn),
	}
}
