// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: protobuf/comm/v1/comm.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseComm_Permmenu_FullMethodName     = "/v1.base.comm.BaseComm/Permmenu"
	BaseComm_Person_FullMethodName       = "/v1.base.comm.BaseComm/Person"
	BaseComm_LoginOut_FullMethodName     = "/v1.base.comm.BaseComm/LoginOut"
	BaseComm_PersonUpdate_FullMethodName = "/v1.base.comm.BaseComm/PersonUpdate"
)

// BaseCommClient is the client API for BaseComm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseCommClient interface {
	// 菜单权限
	Permmenu(ctx context.Context, in *PermmenuRpcInvoke, opts ...grpc.CallOption) (*PermmenuRpcRes, error)
	// 个人信息
	Person(ctx context.Context, in *PersonRpcInvoke, opts ...grpc.CallOption) (*PersonRpcRes, error)
	// 退出登录
	LoginOut(ctx context.Context, in *LoginOutRpcInvoke, opts ...grpc.CallOption) (*LoginOutRes, error)
	// 更新用户信息
	PersonUpdate(ctx context.Context, in *PersonUpdateInvoke, opts ...grpc.CallOption) (*PersonUpdateRes, error)
}

type baseCommClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseCommClient(cc grpc.ClientConnInterface) BaseCommClient {
	return &baseCommClient{cc}
}

func (c *baseCommClient) Permmenu(ctx context.Context, in *PermmenuRpcInvoke, opts ...grpc.CallOption) (*PermmenuRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermmenuRpcRes)
	err := c.cc.Invoke(ctx, BaseComm_Permmenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCommClient) Person(ctx context.Context, in *PersonRpcInvoke, opts ...grpc.CallOption) (*PersonRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonRpcRes)
	err := c.cc.Invoke(ctx, BaseComm_Person_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCommClient) LoginOut(ctx context.Context, in *LoginOutRpcInvoke, opts ...grpc.CallOption) (*LoginOutRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginOutRes)
	err := c.cc.Invoke(ctx, BaseComm_LoginOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseCommClient) PersonUpdate(ctx context.Context, in *PersonUpdateInvoke, opts ...grpc.CallOption) (*PersonUpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonUpdateRes)
	err := c.cc.Invoke(ctx, BaseComm_PersonUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseCommServer is the server API for BaseComm service.
// All implementations must embed UnimplementedBaseCommServer
// for forward compatibility.
type BaseCommServer interface {
	// 菜单权限
	Permmenu(context.Context, *PermmenuRpcInvoke) (*PermmenuRpcRes, error)
	// 个人信息
	Person(context.Context, *PersonRpcInvoke) (*PersonRpcRes, error)
	// 退出登录
	LoginOut(context.Context, *LoginOutRpcInvoke) (*LoginOutRes, error)
	// 更新用户信息
	PersonUpdate(context.Context, *PersonUpdateInvoke) (*PersonUpdateRes, error)
	mustEmbedUnimplementedBaseCommServer()
}

// UnimplementedBaseCommServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseCommServer struct{}

func (UnimplementedBaseCommServer) Permmenu(context.Context, *PermmenuRpcInvoke) (*PermmenuRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Permmenu not implemented")
}
func (UnimplementedBaseCommServer) Person(context.Context, *PersonRpcInvoke) (*PersonRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Person not implemented")
}
func (UnimplementedBaseCommServer) LoginOut(context.Context, *LoginOutRpcInvoke) (*LoginOutRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOut not implemented")
}
func (UnimplementedBaseCommServer) PersonUpdate(context.Context, *PersonUpdateInvoke) (*PersonUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonUpdate not implemented")
}
func (UnimplementedBaseCommServer) mustEmbedUnimplementedBaseCommServer() {}
func (UnimplementedBaseCommServer) testEmbeddedByValue()                  {}

// UnsafeBaseCommServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseCommServer will
// result in compilation errors.
type UnsafeBaseCommServer interface {
	mustEmbedUnimplementedBaseCommServer()
}

func RegisterBaseCommServer(s grpc.ServiceRegistrar, srv BaseCommServer) {
	// If the following call pancis, it indicates UnimplementedBaseCommServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseComm_ServiceDesc, srv)
}

func _BaseComm_Permmenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermmenuRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCommServer).Permmenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseComm_Permmenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCommServer).Permmenu(ctx, req.(*PermmenuRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseComm_Person_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCommServer).Person(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseComm_Person_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCommServer).Person(ctx, req.(*PersonRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseComm_LoginOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginOutRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCommServer).LoginOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseComm_LoginOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCommServer).LoginOut(ctx, req.(*LoginOutRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseComm_PersonUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonUpdateInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseCommServer).PersonUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseComm_PersonUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseCommServer).PersonUpdate(ctx, req.(*PersonUpdateInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseComm_ServiceDesc is the grpc.ServiceDesc for BaseComm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseComm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.base.comm.BaseComm",
	HandlerType: (*BaseCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Permmenu",
			Handler:    _BaseComm_Permmenu_Handler,
		},
		{
			MethodName: "Person",
			Handler:    _BaseComm_Person_Handler,
		},
		{
			MethodName: "LoginOut",
			Handler:    _BaseComm_LoginOut_Handler,
		},
		{
			MethodName: "PersonUpdate",
			Handler:    _BaseComm_PersonUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/comm/v1/comm.proto",
}
