// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: app/admin/manifest/protobuf/open/v1/open.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptchaRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty" v:"required"` // v:required
	Widget        int32                  `protobuf:"varint,2,opt,name=Widget,proto3" json:"Widget,omitempty" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRpcInvoke) Reset() {
	*x = CaptchaRpcInvoke{}
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRpcInvoke) ProtoMessage() {}

func (x *CaptchaRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRpcInvoke.ProtoReflect.Descriptor instead.
func (*CaptchaRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaRpcInvoke) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaRpcInvoke) GetWidget() int32 {
	if x != nil {
		return x.Widget
	}
	return 0
}

type CaptchaRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=CaptchaId,proto3" json:"CaptchaId,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRpcRes) Reset() {
	*x = CaptchaRpcRes{}
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRpcRes) ProtoMessage() {}

func (x *CaptchaRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRpcRes.ProtoReflect.Descriptor instead.
func (*CaptchaRpcRes) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaRpcRes) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaRpcRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LoginRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=CaptchaId,proto3" json:"CaptchaId,omitempty" v:"required" v:"required" v:"required" v:"required" v:"required"`   // v:required
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty" v:"required" v:"required" v:"required" v:"required" v:"required"`     // v:required
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty" v:"required" v:"required" v:"required" v:"required" v:"required"`     // v:required
	VerifyCode    string                 `protobuf:"bytes,4,opt,name=VerifyCode,proto3" json:"VerifyCode,omitempty" v:"required" v:"required" v:"required" v:"required" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRpcInvoke) Reset() {
	*x = LoginRpcInvoke{}
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRpcInvoke) ProtoMessage() {}

func (x *LoginRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRpcInvoke.ProtoReflect.Descriptor instead.
func (*LoginRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRpcInvoke) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *LoginRpcInvoke) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRpcInvoke) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRpcInvoke) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type LoginRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expire        int64                  `protobuf:"varint,1,opt,name=Expire,proto3" json:"Expire,omitempty"`
	RefreshExpire int64                  `protobuf:"varint,2,opt,name=RefreshExpire,proto3" json:"RefreshExpire,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRpcRes) Reset() {
	*x = LoginRpcRes{}
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRpcRes) ProtoMessage() {}

func (x *LoginRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRpcRes.ProtoReflect.Descriptor instead.
func (*LoginRpcRes) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRpcRes) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *LoginRpcRes) GetRefreshExpire() int64 {
	if x != nil {
		return x.RefreshExpire
	}
	return 0
}

func (x *LoginRpcRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginRpcRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshTokenInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenInvoke) Reset() {
	*x = RefreshTokenInvoke{}
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenInvoke) ProtoMessage() {}

func (x *RefreshTokenInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenInvoke.ProtoReflect.Descriptor instead.
func (*RefreshTokenInvoke) Descriptor() ([]byte, []int) {
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenInvoke) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_app_admin_manifest_protobuf_open_v1_open_proto protoreflect.FileDescriptor

var file_app_admin_manifest_protobuf_open_v1_open_proto_rawDesc = string([]byte{
	0x0a, 0x2e, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x22, 0x42,
	0x0a, 0x10, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f,
	0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x22, 0x41, 0x0a, 0x0d, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x70, 0x63,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x70,
	0x74, 0x63, 0x68, 0x61, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x85,
	0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x38, 0x0a, 0x12, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x32, 0xe1, 0x01, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x46, 0x0a,
	0x07, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52,
	0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52,
	0x70, 0x63, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c,
	0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x70, 0x63, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x1a, 0x19, 0x2e, 0x76,
	0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x76, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescOnce sync.Once
	file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescData []byte
)

func file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescGZIP() []byte {
	file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescOnce.Do(func() {
		file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_open_v1_open_proto_rawDesc), len(file_app_admin_manifest_protobuf_open_v1_open_proto_rawDesc)))
	})
	return file_app_admin_manifest_protobuf_open_v1_open_proto_rawDescData
}

var file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_admin_manifest_protobuf_open_v1_open_proto_goTypes = []any{
	(*CaptchaRpcInvoke)(nil),   // 0: v1.base.open.CaptchaRpcInvoke
	(*CaptchaRpcRes)(nil),      // 1: v1.base.open.CaptchaRpcRes
	(*LoginRpcInvoke)(nil),     // 2: v1.base.open.LoginRpcInvoke
	(*LoginRpcRes)(nil),        // 3: v1.base.open.LoginRpcRes
	(*RefreshTokenInvoke)(nil), // 4: v1.base.open.RefreshTokenInvoke
}
var file_app_admin_manifest_protobuf_open_v1_open_proto_depIdxs = []int32{
	0, // 0: v1.base.open.BaseOpen.Captcha:input_type -> v1.base.open.CaptchaRpcInvoke
	2, // 1: v1.base.open.BaseOpen.Login:input_type -> v1.base.open.LoginRpcInvoke
	4, // 2: v1.base.open.BaseOpen.RefreshToken:input_type -> v1.base.open.RefreshTokenInvoke
	1, // 3: v1.base.open.BaseOpen.Captcha:output_type -> v1.base.open.CaptchaRpcRes
	3, // 4: v1.base.open.BaseOpen.Login:output_type -> v1.base.open.LoginRpcRes
	3, // 5: v1.base.open.BaseOpen.RefreshToken:output_type -> v1.base.open.LoginRpcRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_admin_manifest_protobuf_open_v1_open_proto_init() }
func file_app_admin_manifest_protobuf_open_v1_open_proto_init() {
	if File_app_admin_manifest_protobuf_open_v1_open_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_admin_manifest_protobuf_open_v1_open_proto_rawDesc), len(file_app_admin_manifest_protobuf_open_v1_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_admin_manifest_protobuf_open_v1_open_proto_goTypes,
		DependencyIndexes: file_app_admin_manifest_protobuf_open_v1_open_proto_depIdxs,
		MessageInfos:      file_app_admin_manifest_protobuf_open_v1_open_proto_msgTypes,
	}.Build()
	File_app_admin_manifest_protobuf_open_v1_open_proto = out.File
	file_app_admin_manifest_protobuf_open_v1_open_proto_goTypes = nil
	file_app_admin_manifest_protobuf_open_v1_open_proto_depIdxs = nil
}
