// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_sys

import (
	v1 "github.com/vera-byte/vgo/app/admin/api/system/v1"

	"github.com/vera-byte/vgo/utility"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	AdminBaseSysClient v1.BaseSysClient
}

func NewV1() *ControllerV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("admin", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
		utility.AuthInterceptor,
		utility.PageRequestInterceptor,
	))
	return &ControllerV1{
		AdminBaseSysClient: v1.NewBaseSysClient(conn),
	}
}
