// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_comm

import (
	"github.com/vera-byte/vgo/utility"

	"github.com/vera-byte/vgo/app/gateway/api/admin_comm"

	v1 "github.com/vera-byte/vgo/app/admin/api/comm/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	AdminBaseCommClient v1.BaseCommClient
}

func NewV1() admin_comm.IAdminCommV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("admin", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
		utility.AuthInterceptor,
	))
	return &ControllerV1{
		AdminBaseCommClient: v1.NewBaseCommClient(conn),
	}
}
