// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"vgo/app/admin/internal/dao/internal"
)

// baseSysRoleMenuDao is the data access object for the table base_sys_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type baseSysRoleMenuDao struct {
	*internal.BaseSysRoleMenuDao
}

var (
	// BaseSysRoleMenu is a globally accessible object for table base_sys_role_menu operations.
	BaseSysRoleMenu = baseSysRoleMenuDao{internal.NewBaseSysRoleMenuDao()}
)

// Add your custom methods and functionality below.
