// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysRoleDao is the data access object for the table base_sys_role.
// You can define custom methods on it to extend its functionality as needed.
type baseSysRoleDao struct {
	*internal.BaseSysRoleDao
}

var (
	// BaseSysRole is a globally accessible object for table base_sys_role operations.
	BaseSysRole = baseSysRoleDao{internal.NewBaseSysRoleDao()}
)

// Add your custom methods and functionality below.
