// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysUserRoleDao is the data access object for the table base_sys_user_role.
// You can define custom methods on it to extend its functionality as needed.
type baseSysUserRoleDao struct {
	*internal.BaseSysUserRoleDao
}

var (
	// BaseSysUserRole is a globally accessible object for table base_sys_user_role operations.
	BaseSysUserRole = baseSysUserRoleDao{internal.NewBaseSysUserRoleDao()}
)

// Add your custom methods and functionality below.
