// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysUserDao is the data access object for the table base_sys_user.
// You can define custom methods on it to extend its functionality as needed.
type baseSysUserDao struct {
	*internal.BaseSysUserDao
}

var (
	// BaseSysUser is a globally accessible object for table base_sys_user operations.
	BaseSysUser = baseSysUserDao{internal.NewBaseSysUserDao()}
)

// Add your custom methods and functionality below.
