// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysRoleDepartmentDao is the data access object for the table base_sys_role_department.
// You can define custom methods on it to extend its functionality as needed.
type baseSysRoleDepartmentDao struct {
	*internal.BaseSysRoleDepartmentDao
}

var (
	// BaseSysRoleDepartment is a globally accessible object for table base_sys_role_department operations.
	BaseSysRoleDepartment = baseSysRoleDepartmentDao{internal.NewBaseSysRoleDepartmentDao()}
)

// Add your custom methods and functionality below.
