// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"vgo/app/admin/internal/dao/internal"
)

// baseSysLogDao is the data access object for the table base_sys_log.
// You can define custom methods on it to extend its functionality as needed.
type baseSysLogDao struct {
	*internal.BaseSysLogDao
}

var (
	// BaseSysLog is a globally accessible object for table base_sys_log operations.
	BaseSysLog = baseSysLogDao{internal.NewBaseSysLogDao()}
)

// Add your custom methods and functionality below.
