// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysDepartmentDao is the data access object for the table base_sys_department.
// You can define custom methods on it to extend its functionality as needed.
type baseSysDepartmentDao struct {
	*internal.BaseSysDepartmentDao
}

var (
	// BaseSysDepartment is a globally accessible object for table base_sys_department operations.
	BaseSysDepartment = baseSysDepartmentDao{internal.NewBaseSysDepartmentDao()}
)

// Add your custom methods and functionality below.
