// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysParamDao is the data access object for the table base_sys_param.
// You can define custom methods on it to extend its functionality as needed.
type baseSysParamDao struct {
	*internal.BaseSysParamDao
}

var (
	// BaseSysParam is a globally accessible object for table base_sys_param operations.
	BaseSysParam = baseSysParamDao{internal.NewBaseSysParamDao()}
)

// Add your custom methods and functionality below.
