// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/vera-byte/vgo/app/admin/internal/dao/internal"
)

// baseSysMenuDao is the data access object for the table base_sys_menu.
// You can define custom methods on it to extend its functionality as needed.
type baseSysMenuDao struct {
	*internal.BaseSysMenuDao
}

var (
	// BaseSysMenu is a globally accessible object for table base_sys_menu operations.
	BaseSysMenu = baseSysMenuDao{internal.NewBaseSysMenuDao()}
)

// Add your custom methods and functionality below.
