// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"vgo/app/admin/internal/dao/internal"
)

// internalBaseSysRoleMenuDao is an internal type for wrapping the internal DAO implementation.
type internalBaseSysRoleMenuDao = *internal.BaseSysRoleMenuDao

// baseSysRoleMenuDao is the data access object for the table base_sys_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type baseSysRoleMenuDao struct {
	internalBaseSysRoleMenuDao
}

var (
	// BaseSysRoleMenu is a globally accessible object for table base_sys_role_menu operations.
	BaseSysRoleMenu = baseSysRoleMenuDao{
		internal.NewBaseSysRoleMenuDao(),
	}
)

// Add your custom methods and functionality below.
