// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: app/v1/base_sys_department.crud.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysDepartment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                 // ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dc:"创建时间"`  // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" dc:"更新时间"`  // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`   // 租户ID
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty" dc:"部门名称"`            // 部门名称
	ParentId      int32                  `protobuf:"varint,6,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"上级部门ID"` // 上级部门ID
	OrderNum      int32                  `protobuf:"varint,7,opt,name=OrderNum,proto3" json:"OrderNum,omitempty" dc:"排序"`     // 排序
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"软删除时间"` // 软删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartment) Reset() {
	*x = BaseSysDepartment{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartment) ProtoMessage() {}

func (x *BaseSysDepartment) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartment.ProtoReflect.Descriptor instead.
func (*BaseSysDepartment) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysDepartment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysDepartment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseSysDepartment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BaseSysDepartment) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysDepartment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseSysDepartment) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *BaseSysDepartment) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *BaseSysDepartment) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type BaseSysDepartmentPageRpcInvoke struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseSysDepartment *BaseSysDepartment     `protobuf:"bytes,1,opt,name=BaseSysDepartment,proto3" json:"BaseSysDepartment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseSysDepartmentPageRpcInvoke) Reset() {
	*x = BaseSysDepartmentPageRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentPageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentPageRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentPageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentPageRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentPageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{1}
}

func (x *BaseSysDepartmentPageRpcInvoke) GetBaseSysDepartment() *BaseSysDepartment {
	if x != nil {
		return x.BaseSysDepartment
	}
	return nil
}

type BaseSysDepartmentPageRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentPageRpcRes) Reset() {
	*x = BaseSysDepartmentPageRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentPageRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentPageRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentPageRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentPageRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentPageRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{2}
}

type BaseSysDepartmentListRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentListRpcInvoke) Reset() {
	*x = BaseSysDepartmentListRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentListRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentListRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentListRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentListRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentListRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{3}
}

type BaseSysDepartmentListRpcRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseSysDepartment []*BaseSysDepartment   `protobuf:"bytes,1,rep,name=BaseSysDepartment,proto3" json:"BaseSysDepartment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseSysDepartmentListRpcRes) Reset() {
	*x = BaseSysDepartmentListRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentListRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentListRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentListRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentListRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentListRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{4}
}

func (x *BaseSysDepartmentListRpcRes) GetBaseSysDepartment() []*BaseSysDepartment {
	if x != nil {
		return x.BaseSysDepartment
	}
	return nil
}

type BaseSysDepartmentAddRpcInvoke struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseSysDepartment *BaseSysDepartment     `protobuf:"bytes,1,opt,name=BaseSysDepartment,proto3" json:"BaseSysDepartment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseSysDepartmentAddRpcInvoke) Reset() {
	*x = BaseSysDepartmentAddRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentAddRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentAddRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentAddRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentAddRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentAddRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{5}
}

func (x *BaseSysDepartmentAddRpcInvoke) GetBaseSysDepartment() *BaseSysDepartment {
	if x != nil {
		return x.BaseSysDepartment
	}
	return nil
}

type BaseSysDepartmentAddRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentAddRpcRes) Reset() {
	*x = BaseSysDepartmentAddRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentAddRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentAddRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentAddRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentAddRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentAddRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{6}
}

type BaseSysDepartmentUpdateRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentUpdateRpcInvoke) Reset() {
	*x = BaseSysDepartmentUpdateRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentUpdateRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentUpdateRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentUpdateRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentUpdateRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentUpdateRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{7}
}

func (x *BaseSysDepartmentUpdateRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysDepartmentUpdateRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentUpdateRpcRes) Reset() {
	*x = BaseSysDepartmentUpdateRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentUpdateRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentUpdateRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentUpdateRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentUpdateRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentUpdateRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{8}
}

type BaseSysDepartmentInfoRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentInfoRpcInvoke) Reset() {
	*x = BaseSysDepartmentInfoRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentInfoRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentInfoRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentInfoRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentInfoRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentInfoRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{9}
}

func (x *BaseSysDepartmentInfoRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysDepartmentInfoRpcRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseSysDepartment *BaseSysDepartment     `protobuf:"bytes,1,opt,name=BaseSysDepartment,proto3" json:"BaseSysDepartment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseSysDepartmentInfoRpcRes) Reset() {
	*x = BaseSysDepartmentInfoRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentInfoRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentInfoRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentInfoRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentInfoRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentInfoRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{10}
}

func (x *BaseSysDepartmentInfoRpcRes) GetBaseSysDepartment() *BaseSysDepartment {
	if x != nil {
		return x.BaseSysDepartment
	}
	return nil
}

type BaseSysDepartmentDeleteRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentDeleteRpcInvoke) Reset() {
	*x = BaseSysDepartmentDeleteRpcInvoke{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentDeleteRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentDeleteRpcInvoke) ProtoMessage() {}

func (x *BaseSysDepartmentDeleteRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentDeleteRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentDeleteRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{11}
}

func (x *BaseSysDepartmentDeleteRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysDepartmentDeleteRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysDepartmentDeleteRpcRes) Reset() {
	*x = BaseSysDepartmentDeleteRpcRes{}
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysDepartmentDeleteRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysDepartmentDeleteRpcRes) ProtoMessage() {}

func (x *BaseSysDepartmentDeleteRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_department_crud_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysDepartmentDeleteRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysDepartmentDeleteRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_department_crud_proto_rawDescGZIP(), []int{12}
}

var File_app_v1_base_sys_department_crud_proto protoreflect.FileDescriptor

const file_app_v1_base_sys_department_crud_proto_rawDesc = "" +
	"\n" +
	"%app/v1/base_sys_department.crud.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\x11BaseSysDepartment\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12\x1a\n" +
	"\bParentId\x18\x06 \x01(\x05R\bParentId\x12\x1a\n" +
	"\bOrderNum\x18\a \x01(\x05R\bOrderNum\x128\n" +
	"\tDeletedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\"f\n" +
	"\x1eBaseSysDepartmentPageRpcInvoke\x12D\n" +
	"\x11BaseSysDepartment\x18\x01 \x01(\v2\x16.api.BaseSysDepartmentR\x11BaseSysDepartment\"\x1d\n" +
	"\x1bBaseSysDepartmentPageRpcRes\" \n" +
	"\x1eBaseSysDepartmentListRpcInvoke\"c\n" +
	"\x1bBaseSysDepartmentListRpcRes\x12D\n" +
	"\x11BaseSysDepartment\x18\x01 \x03(\v2\x16.api.BaseSysDepartmentR\x11BaseSysDepartment\"e\n" +
	"\x1dBaseSysDepartmentAddRpcInvoke\x12D\n" +
	"\x11BaseSysDepartment\x18\x01 \x01(\v2\x16.api.BaseSysDepartmentR\x11BaseSysDepartment\"\x1c\n" +
	"\x1aBaseSysDepartmentAddRpcRes\"2\n" +
	" BaseSysDepartmentUpdateRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"\x1f\n" +
	"\x1dBaseSysDepartmentUpdateRpcRes\"0\n" +
	"\x1eBaseSysDepartmentInfoRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"c\n" +
	"\x1bBaseSysDepartmentInfoRpcRes\x12D\n" +
	"\x11BaseSysDepartment\x18\x01 \x01(\v2\x16.api.BaseSysDepartmentR\x11BaseSysDepartment\"2\n" +
	" BaseSysDepartmentDeleteRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"\x1f\n" +
	"\x1dBaseSysDepartmentDeleteRpcRes2\x81\x04\n" +
	"\x1cBaseSysDepartmentCrudService\x12J\n" +
	"\x03Add\x12\".api.BaseSysDepartmentAddRpcInvoke\x1a\x1f.api.BaseSysDepartmentAddRpcRes\x12S\n" +
	"\x06Update\x12%.api.BaseSysDepartmentUpdateRpcInvoke\x1a\".api.BaseSysDepartmentUpdateRpcRes\x12M\n" +
	"\x04Info\x12#.api.BaseSysDepartmentInfoRpcInvoke\x1a .api.BaseSysDepartmentInfoRpcRes\x12S\n" +
	"\x06Delete\x12%.api.BaseSysDepartmentDeleteRpcInvoke\x1a\".api.BaseSysDepartmentDeleteRpcRes\x12M\n" +
	"\x04Page\x12#.api.BaseSysDepartmentPageRpcInvoke\x1a .api.BaseSysDepartmentPageRpcRes\x12M\n" +
	"\x04List\x12#.api.BaseSysDepartmentListRpcInvoke\x1a .api.BaseSysDepartmentListRpcResB8Z6github.com/vera-byte/vgo/vgo-tools/api/v1/app/protobufb\x06proto3"

var (
	file_app_v1_base_sys_department_crud_proto_rawDescOnce sync.Once
	file_app_v1_base_sys_department_crud_proto_rawDescData []byte
)

func file_app_v1_base_sys_department_crud_proto_rawDescGZIP() []byte {
	file_app_v1_base_sys_department_crud_proto_rawDescOnce.Do(func() {
		file_app_v1_base_sys_department_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_v1_base_sys_department_crud_proto_rawDesc), len(file_app_v1_base_sys_department_crud_proto_rawDesc)))
	})
	return file_app_v1_base_sys_department_crud_proto_rawDescData
}

var file_app_v1_base_sys_department_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_v1_base_sys_department_crud_proto_goTypes = []any{
	(*BaseSysDepartment)(nil),                // 0: api.BaseSysDepartment
	(*BaseSysDepartmentPageRpcInvoke)(nil),   // 1: api.BaseSysDepartmentPageRpcInvoke
	(*BaseSysDepartmentPageRpcRes)(nil),      // 2: api.BaseSysDepartmentPageRpcRes
	(*BaseSysDepartmentListRpcInvoke)(nil),   // 3: api.BaseSysDepartmentListRpcInvoke
	(*BaseSysDepartmentListRpcRes)(nil),      // 4: api.BaseSysDepartmentListRpcRes
	(*BaseSysDepartmentAddRpcInvoke)(nil),    // 5: api.BaseSysDepartmentAddRpcInvoke
	(*BaseSysDepartmentAddRpcRes)(nil),       // 6: api.BaseSysDepartmentAddRpcRes
	(*BaseSysDepartmentUpdateRpcInvoke)(nil), // 7: api.BaseSysDepartmentUpdateRpcInvoke
	(*BaseSysDepartmentUpdateRpcRes)(nil),    // 8: api.BaseSysDepartmentUpdateRpcRes
	(*BaseSysDepartmentInfoRpcInvoke)(nil),   // 9: api.BaseSysDepartmentInfoRpcInvoke
	(*BaseSysDepartmentInfoRpcRes)(nil),      // 10: api.BaseSysDepartmentInfoRpcRes
	(*BaseSysDepartmentDeleteRpcInvoke)(nil), // 11: api.BaseSysDepartmentDeleteRpcInvoke
	(*BaseSysDepartmentDeleteRpcRes)(nil),    // 12: api.BaseSysDepartmentDeleteRpcRes
	(*timestamppb.Timestamp)(nil),            // 13: google.protobuf.Timestamp
}
var file_app_v1_base_sys_department_crud_proto_depIdxs = []int32{
	13, // 0: api.BaseSysDepartment.CreatedAt:type_name -> google.protobuf.Timestamp
	13, // 1: api.BaseSysDepartment.UpdatedAt:type_name -> google.protobuf.Timestamp
	13, // 2: api.BaseSysDepartment.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: api.BaseSysDepartmentPageRpcInvoke.BaseSysDepartment:type_name -> api.BaseSysDepartment
	0,  // 4: api.BaseSysDepartmentListRpcRes.BaseSysDepartment:type_name -> api.BaseSysDepartment
	0,  // 5: api.BaseSysDepartmentAddRpcInvoke.BaseSysDepartment:type_name -> api.BaseSysDepartment
	0,  // 6: api.BaseSysDepartmentInfoRpcRes.BaseSysDepartment:type_name -> api.BaseSysDepartment
	5,  // 7: api.BaseSysDepartmentCrudService.Add:input_type -> api.BaseSysDepartmentAddRpcInvoke
	7,  // 8: api.BaseSysDepartmentCrudService.Update:input_type -> api.BaseSysDepartmentUpdateRpcInvoke
	9,  // 9: api.BaseSysDepartmentCrudService.Info:input_type -> api.BaseSysDepartmentInfoRpcInvoke
	11, // 10: api.BaseSysDepartmentCrudService.Delete:input_type -> api.BaseSysDepartmentDeleteRpcInvoke
	1,  // 11: api.BaseSysDepartmentCrudService.Page:input_type -> api.BaseSysDepartmentPageRpcInvoke
	3,  // 12: api.BaseSysDepartmentCrudService.List:input_type -> api.BaseSysDepartmentListRpcInvoke
	6,  // 13: api.BaseSysDepartmentCrudService.Add:output_type -> api.BaseSysDepartmentAddRpcRes
	8,  // 14: api.BaseSysDepartmentCrudService.Update:output_type -> api.BaseSysDepartmentUpdateRpcRes
	10, // 15: api.BaseSysDepartmentCrudService.Info:output_type -> api.BaseSysDepartmentInfoRpcRes
	12, // 16: api.BaseSysDepartmentCrudService.Delete:output_type -> api.BaseSysDepartmentDeleteRpcRes
	2,  // 17: api.BaseSysDepartmentCrudService.Page:output_type -> api.BaseSysDepartmentPageRpcRes
	4,  // 18: api.BaseSysDepartmentCrudService.List:output_type -> api.BaseSysDepartmentListRpcRes
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_v1_base_sys_department_crud_proto_init() }
func file_app_v1_base_sys_department_crud_proto_init() {
	if File_app_v1_base_sys_department_crud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_v1_base_sys_department_crud_proto_rawDesc), len(file_app_v1_base_sys_department_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_v1_base_sys_department_crud_proto_goTypes,
		DependencyIndexes: file_app_v1_base_sys_department_crud_proto_depIdxs,
		MessageInfos:      file_app_v1_base_sys_department_crud_proto_msgTypes,
	}.Build()
	File_app_v1_base_sys_department_crud_proto = out.File
	file_app_v1_base_sys_department_crud_proto_goTypes = nil
	file_app_v1_base_sys_department_crud_proto_depIdxs = nil
}
