// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: app/v1/base_sys_conf.crud.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseSysConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"`                 // ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dc:"创建时间"`  // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" dc:"更新时间"`  // 更新时间
	TenantId      int32                  `protobuf:"varint,4,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户ID"`   // 租户ID
	CKey          string                 `protobuf:"bytes,5,opt,name=CKey,proto3" json:"CKey,omitempty" dc:"配置键"`             // 配置键
	CValue        string                 `protobuf:"bytes,6,opt,name=CValue,proto3" json:"CValue,omitempty" dc:"配置值"`         // 配置值
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"软删除时间"` // 软删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConf) Reset() {
	*x = BaseSysConf{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConf) ProtoMessage() {}

func (x *BaseSysConf) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConf.ProtoReflect.Descriptor instead.
func (*BaseSysConf) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{0}
}

func (x *BaseSysConf) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseSysConf) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseSysConf) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BaseSysConf) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BaseSysConf) GetCKey() string {
	if x != nil {
		return x.CKey
	}
	return ""
}

func (x *BaseSysConf) GetCValue() string {
	if x != nil {
		return x.CValue
	}
	return ""
}

func (x *BaseSysConf) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type BaseSysConfListRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfListRpcInvoke) Reset() {
	*x = BaseSysConfListRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfListRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfListRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfListRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfListRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfListRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{1}
}

type BaseSysConfListRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSysConf   []*BaseSysConf         `protobuf:"bytes,1,rep,name=BaseSysConf,proto3" json:"BaseSysConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfListRpcRes) Reset() {
	*x = BaseSysConfListRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfListRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfListRpcRes) ProtoMessage() {}

func (x *BaseSysConfListRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfListRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfListRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{2}
}

func (x *BaseSysConfListRpcRes) GetBaseSysConf() []*BaseSysConf {
	if x != nil {
		return x.BaseSysConf
	}
	return nil
}

type BaseSysConfAddRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSysConf   *BaseSysConf           `protobuf:"bytes,1,opt,name=BaseSysConf,proto3" json:"BaseSysConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfAddRpcInvoke) Reset() {
	*x = BaseSysConfAddRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfAddRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfAddRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfAddRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfAddRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfAddRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{3}
}

func (x *BaseSysConfAddRpcInvoke) GetBaseSysConf() *BaseSysConf {
	if x != nil {
		return x.BaseSysConf
	}
	return nil
}

type BaseSysConfAddRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfAddRpcRes) Reset() {
	*x = BaseSysConfAddRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfAddRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfAddRpcRes) ProtoMessage() {}

func (x *BaseSysConfAddRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfAddRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfAddRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{4}
}

type BaseSysConfUpdateRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfUpdateRpcInvoke) Reset() {
	*x = BaseSysConfUpdateRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfUpdateRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfUpdateRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfUpdateRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfUpdateRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfUpdateRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{5}
}

func (x *BaseSysConfUpdateRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysConfUpdateRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfUpdateRpcRes) Reset() {
	*x = BaseSysConfUpdateRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfUpdateRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfUpdateRpcRes) ProtoMessage() {}

func (x *BaseSysConfUpdateRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfUpdateRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfUpdateRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{6}
}

type BaseSysConfInfoRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfInfoRpcInvoke) Reset() {
	*x = BaseSysConfInfoRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfInfoRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfInfoRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfInfoRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfInfoRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfInfoRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{7}
}

func (x *BaseSysConfInfoRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysConfInfoRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSysConf   *BaseSysConf           `protobuf:"bytes,1,opt,name=BaseSysConf,proto3" json:"BaseSysConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfInfoRpcRes) Reset() {
	*x = BaseSysConfInfoRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfInfoRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfInfoRpcRes) ProtoMessage() {}

func (x *BaseSysConfInfoRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfInfoRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfInfoRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{8}
}

func (x *BaseSysConfInfoRpcRes) GetBaseSysConf() *BaseSysConf {
	if x != nil {
		return x.BaseSysConf
	}
	return nil
}

type BaseSysConfDeleteRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"ID"` // ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfDeleteRpcInvoke) Reset() {
	*x = BaseSysConfDeleteRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfDeleteRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfDeleteRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfDeleteRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfDeleteRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfDeleteRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{9}
}

func (x *BaseSysConfDeleteRpcInvoke) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaseSysConfDeleteRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfDeleteRpcRes) Reset() {
	*x = BaseSysConfDeleteRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfDeleteRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfDeleteRpcRes) ProtoMessage() {}

func (x *BaseSysConfDeleteRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfDeleteRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfDeleteRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{10}
}

type BaseSysConfPageRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSysConf   *BaseSysConf           `protobuf:"bytes,1,opt,name=BaseSysConf,proto3" json:"BaseSysConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfPageRpcInvoke) Reset() {
	*x = BaseSysConfPageRpcInvoke{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfPageRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfPageRpcInvoke) ProtoMessage() {}

func (x *BaseSysConfPageRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfPageRpcInvoke.ProtoReflect.Descriptor instead.
func (*BaseSysConfPageRpcInvoke) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{11}
}

func (x *BaseSysConfPageRpcInvoke) GetBaseSysConf() *BaseSysConf {
	if x != nil {
		return x.BaseSysConf
	}
	return nil
}

type BaseSysConfPageRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseSysConfPageRpcRes) Reset() {
	*x = BaseSysConfPageRpcRes{}
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseSysConfPageRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseSysConfPageRpcRes) ProtoMessage() {}

func (x *BaseSysConfPageRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_base_sys_conf_crud_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseSysConfPageRpcRes.ProtoReflect.Descriptor instead.
func (*BaseSysConfPageRpcRes) Descriptor() ([]byte, []int) {
	return file_app_v1_base_sys_conf_crud_proto_rawDescGZIP(), []int{12}
}

var File_app_v1_base_sys_conf_crud_proto protoreflect.FileDescriptor

const file_app_v1_base_sys_conf_crud_proto_rawDesc = "" +
	"\n" +
	"\x1fapp/v1/base_sys_conf.crud.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n" +
	"\vBaseSysConf\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1a\n" +
	"\bTenantId\x18\x04 \x01(\x05R\bTenantId\x12\x12\n" +
	"\x04CKey\x18\x05 \x01(\tR\x04CKey\x12\x16\n" +
	"\x06CValue\x18\x06 \x01(\tR\x06CValue\x128\n" +
	"\tDeletedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\"\x1a\n" +
	"\x18BaseSysConfListRpcInvoke\"K\n" +
	"\x15BaseSysConfListRpcRes\x122\n" +
	"\vBaseSysConf\x18\x01 \x03(\v2\x10.api.BaseSysConfR\vBaseSysConf\"M\n" +
	"\x17BaseSysConfAddRpcInvoke\x122\n" +
	"\vBaseSysConf\x18\x01 \x01(\v2\x10.api.BaseSysConfR\vBaseSysConf\"\x16\n" +
	"\x14BaseSysConfAddRpcRes\",\n" +
	"\x1aBaseSysConfUpdateRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"\x19\n" +
	"\x17BaseSysConfUpdateRpcRes\"*\n" +
	"\x18BaseSysConfInfoRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"K\n" +
	"\x15BaseSysConfInfoRpcRes\x122\n" +
	"\vBaseSysConf\x18\x01 \x01(\v2\x10.api.BaseSysConfR\vBaseSysConf\",\n" +
	"\x1aBaseSysConfDeleteRpcInvoke\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\"\x19\n" +
	"\x17BaseSysConfDeleteRpcRes\"N\n" +
	"\x18BaseSysConfPageRpcInvoke\x122\n" +
	"\vBaseSysConf\x18\x01 \x01(\v2\x10.api.BaseSysConfR\vBaseSysConf\"\x17\n" +
	"\x15BaseSysConfPageRpcRes2\xb3\x03\n" +
	"\x16BaseSysConfCrudService\x12>\n" +
	"\x03Add\x12\x1c.api.BaseSysConfAddRpcInvoke\x1a\x19.api.BaseSysConfAddRpcRes\x12G\n" +
	"\x06Update\x12\x1f.api.BaseSysConfUpdateRpcInvoke\x1a\x1c.api.BaseSysConfUpdateRpcRes\x12A\n" +
	"\x04Info\x12\x1d.api.BaseSysConfInfoRpcInvoke\x1a\x1a.api.BaseSysConfInfoRpcRes\x12G\n" +
	"\x06Delete\x12\x1f.api.BaseSysConfDeleteRpcInvoke\x1a\x1c.api.BaseSysConfDeleteRpcRes\x12A\n" +
	"\x04Page\x12\x1d.api.BaseSysConfPageRpcInvoke\x1a\x1a.api.BaseSysConfPageRpcRes\x12A\n" +
	"\x04List\x12\x1d.api.BaseSysConfListRpcInvoke\x1a\x1a.api.BaseSysConfListRpcResB8Z6github.com/vera-byte/vgo/vgo-tools/api/v1/app/protobufb\x06proto3"

var (
	file_app_v1_base_sys_conf_crud_proto_rawDescOnce sync.Once
	file_app_v1_base_sys_conf_crud_proto_rawDescData []byte
)

func file_app_v1_base_sys_conf_crud_proto_rawDescGZIP() []byte {
	file_app_v1_base_sys_conf_crud_proto_rawDescOnce.Do(func() {
		file_app_v1_base_sys_conf_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_v1_base_sys_conf_crud_proto_rawDesc), len(file_app_v1_base_sys_conf_crud_proto_rawDesc)))
	})
	return file_app_v1_base_sys_conf_crud_proto_rawDescData
}

var file_app_v1_base_sys_conf_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_v1_base_sys_conf_crud_proto_goTypes = []any{
	(*BaseSysConf)(nil),                // 0: api.BaseSysConf
	(*BaseSysConfListRpcInvoke)(nil),   // 1: api.BaseSysConfListRpcInvoke
	(*BaseSysConfListRpcRes)(nil),      // 2: api.BaseSysConfListRpcRes
	(*BaseSysConfAddRpcInvoke)(nil),    // 3: api.BaseSysConfAddRpcInvoke
	(*BaseSysConfAddRpcRes)(nil),       // 4: api.BaseSysConfAddRpcRes
	(*BaseSysConfUpdateRpcInvoke)(nil), // 5: api.BaseSysConfUpdateRpcInvoke
	(*BaseSysConfUpdateRpcRes)(nil),    // 6: api.BaseSysConfUpdateRpcRes
	(*BaseSysConfInfoRpcInvoke)(nil),   // 7: api.BaseSysConfInfoRpcInvoke
	(*BaseSysConfInfoRpcRes)(nil),      // 8: api.BaseSysConfInfoRpcRes
	(*BaseSysConfDeleteRpcInvoke)(nil), // 9: api.BaseSysConfDeleteRpcInvoke
	(*BaseSysConfDeleteRpcRes)(nil),    // 10: api.BaseSysConfDeleteRpcRes
	(*BaseSysConfPageRpcInvoke)(nil),   // 11: api.BaseSysConfPageRpcInvoke
	(*BaseSysConfPageRpcRes)(nil),      // 12: api.BaseSysConfPageRpcRes
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_app_v1_base_sys_conf_crud_proto_depIdxs = []int32{
	13, // 0: api.BaseSysConf.CreatedAt:type_name -> google.protobuf.Timestamp
	13, // 1: api.BaseSysConf.UpdatedAt:type_name -> google.protobuf.Timestamp
	13, // 2: api.BaseSysConf.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: api.BaseSysConfListRpcRes.BaseSysConf:type_name -> api.BaseSysConf
	0,  // 4: api.BaseSysConfAddRpcInvoke.BaseSysConf:type_name -> api.BaseSysConf
	0,  // 5: api.BaseSysConfInfoRpcRes.BaseSysConf:type_name -> api.BaseSysConf
	0,  // 6: api.BaseSysConfPageRpcInvoke.BaseSysConf:type_name -> api.BaseSysConf
	3,  // 7: api.BaseSysConfCrudService.Add:input_type -> api.BaseSysConfAddRpcInvoke
	5,  // 8: api.BaseSysConfCrudService.Update:input_type -> api.BaseSysConfUpdateRpcInvoke
	7,  // 9: api.BaseSysConfCrudService.Info:input_type -> api.BaseSysConfInfoRpcInvoke
	9,  // 10: api.BaseSysConfCrudService.Delete:input_type -> api.BaseSysConfDeleteRpcInvoke
	11, // 11: api.BaseSysConfCrudService.Page:input_type -> api.BaseSysConfPageRpcInvoke
	1,  // 12: api.BaseSysConfCrudService.List:input_type -> api.BaseSysConfListRpcInvoke
	4,  // 13: api.BaseSysConfCrudService.Add:output_type -> api.BaseSysConfAddRpcRes
	6,  // 14: api.BaseSysConfCrudService.Update:output_type -> api.BaseSysConfUpdateRpcRes
	8,  // 15: api.BaseSysConfCrudService.Info:output_type -> api.BaseSysConfInfoRpcRes
	10, // 16: api.BaseSysConfCrudService.Delete:output_type -> api.BaseSysConfDeleteRpcRes
	12, // 17: api.BaseSysConfCrudService.Page:output_type -> api.BaseSysConfPageRpcRes
	2,  // 18: api.BaseSysConfCrudService.List:output_type -> api.BaseSysConfListRpcRes
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_v1_base_sys_conf_crud_proto_init() }
func file_app_v1_base_sys_conf_crud_proto_init() {
	if File_app_v1_base_sys_conf_crud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_v1_base_sys_conf_crud_proto_rawDesc), len(file_app_v1_base_sys_conf_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_v1_base_sys_conf_crud_proto_goTypes,
		DependencyIndexes: file_app_v1_base_sys_conf_crud_proto_depIdxs,
		MessageInfos:      file_app_v1_base_sys_conf_crud_proto_msgTypes,
	}.Build()
	File_app_v1_base_sys_conf_crud_proto = out.File
	file_app_v1_base_sys_conf_crud_proto_goTypes = nil
	file_app_v1_base_sys_conf_crud_proto_depIdxs = nil
}
