// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: app/v1/base_sys_conf.crud.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseSysConfCrudService_Add_FullMethodName    = "/api.BaseSysConfCrudService/Add"
	BaseSysConfCrudService_Update_FullMethodName = "/api.BaseSysConfCrudService/Update"
	BaseSysConfCrudService_Info_FullMethodName   = "/api.BaseSysConfCrudService/Info"
	BaseSysConfCrudService_Delete_FullMethodName = "/api.BaseSysConfCrudService/Delete"
	BaseSysConfCrudService_Page_FullMethodName   = "/api.BaseSysConfCrudService/Page"
	BaseSysConfCrudService_List_FullMethodName   = "/api.BaseSysConfCrudService/List"
)

// BaseSysConfCrudServiceClient is the client API for BaseSysConfCrudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseSysConfCrudServiceClient interface {
	// Add
	Add(ctx context.Context, in *BaseSysConfAddRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfAddRpcRes, error)
	// Update
	Update(ctx context.Context, in *BaseSysConfUpdateRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfUpdateRpcRes, error)
	// Info
	Info(ctx context.Context, in *BaseSysConfInfoRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfInfoRpcRes, error)
	// Delete
	Delete(ctx context.Context, in *BaseSysConfDeleteRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfDeleteRpcRes, error)
	// Page
	Page(ctx context.Context, in *BaseSysConfPageRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfPageRpcRes, error)
	// List
	List(ctx context.Context, in *BaseSysConfListRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfListRpcRes, error)
}

type baseSysConfCrudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseSysConfCrudServiceClient(cc grpc.ClientConnInterface) BaseSysConfCrudServiceClient {
	return &baseSysConfCrudServiceClient{cc}
}

func (c *baseSysConfCrudServiceClient) Add(ctx context.Context, in *BaseSysConfAddRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfAddRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfAddRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysConfCrudServiceClient) Update(ctx context.Context, in *BaseSysConfUpdateRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfUpdateRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfUpdateRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysConfCrudServiceClient) Info(ctx context.Context, in *BaseSysConfInfoRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfInfoRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfInfoRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysConfCrudServiceClient) Delete(ctx context.Context, in *BaseSysConfDeleteRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfDeleteRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfDeleteRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysConfCrudServiceClient) Page(ctx context.Context, in *BaseSysConfPageRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfPageRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfPageRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_Page_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysConfCrudServiceClient) List(ctx context.Context, in *BaseSysConfListRpcInvoke, opts ...grpc.CallOption) (*BaseSysConfListRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysConfListRpcRes)
	err := c.cc.Invoke(ctx, BaseSysConfCrudService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseSysConfCrudServiceServer is the server API for BaseSysConfCrudService service.
// All implementations must embed UnimplementedBaseSysConfCrudServiceServer
// for forward compatibility.
type BaseSysConfCrudServiceServer interface {
	// Add
	Add(context.Context, *BaseSysConfAddRpcInvoke) (*BaseSysConfAddRpcRes, error)
	// Update
	Update(context.Context, *BaseSysConfUpdateRpcInvoke) (*BaseSysConfUpdateRpcRes, error)
	// Info
	Info(context.Context, *BaseSysConfInfoRpcInvoke) (*BaseSysConfInfoRpcRes, error)
	// Delete
	Delete(context.Context, *BaseSysConfDeleteRpcInvoke) (*BaseSysConfDeleteRpcRes, error)
	// Page
	Page(context.Context, *BaseSysConfPageRpcInvoke) (*BaseSysConfPageRpcRes, error)
	// List
	List(context.Context, *BaseSysConfListRpcInvoke) (*BaseSysConfListRpcRes, error)
	mustEmbedUnimplementedBaseSysConfCrudServiceServer()
}

// UnimplementedBaseSysConfCrudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseSysConfCrudServiceServer struct{}

func (UnimplementedBaseSysConfCrudServiceServer) Add(context.Context, *BaseSysConfAddRpcInvoke) (*BaseSysConfAddRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) Update(context.Context, *BaseSysConfUpdateRpcInvoke) (*BaseSysConfUpdateRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) Info(context.Context, *BaseSysConfInfoRpcInvoke) (*BaseSysConfInfoRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) Delete(context.Context, *BaseSysConfDeleteRpcInvoke) (*BaseSysConfDeleteRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) Page(context.Context, *BaseSysConfPageRpcInvoke) (*BaseSysConfPageRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Page not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) List(context.Context, *BaseSysConfListRpcInvoke) (*BaseSysConfListRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBaseSysConfCrudServiceServer) mustEmbedUnimplementedBaseSysConfCrudServiceServer() {
}
func (UnimplementedBaseSysConfCrudServiceServer) testEmbeddedByValue() {}

// UnsafeBaseSysConfCrudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseSysConfCrudServiceServer will
// result in compilation errors.
type UnsafeBaseSysConfCrudServiceServer interface {
	mustEmbedUnimplementedBaseSysConfCrudServiceServer()
}

func RegisterBaseSysConfCrudServiceServer(s grpc.ServiceRegistrar, srv BaseSysConfCrudServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseSysConfCrudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseSysConfCrudService_ServiceDesc, srv)
}

func _BaseSysConfCrudService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfAddRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).Add(ctx, req.(*BaseSysConfAddRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysConfCrudService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfUpdateRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).Update(ctx, req.(*BaseSysConfUpdateRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysConfCrudService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfInfoRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).Info(ctx, req.(*BaseSysConfInfoRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysConfCrudService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfDeleteRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).Delete(ctx, req.(*BaseSysConfDeleteRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysConfCrudService_Page_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfPageRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).Page(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_Page_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).Page(ctx, req.(*BaseSysConfPageRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysConfCrudService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysConfListRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysConfCrudServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysConfCrudService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysConfCrudServiceServer).List(ctx, req.(*BaseSysConfListRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseSysConfCrudService_ServiceDesc is the grpc.ServiceDesc for BaseSysConfCrudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseSysConfCrudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BaseSysConfCrudService",
	HandlerType: (*BaseSysConfCrudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BaseSysConfCrudService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BaseSysConfCrudService_Update_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _BaseSysConfCrudService_Info_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BaseSysConfCrudService_Delete_Handler,
		},
		{
			MethodName: "Page",
			Handler:    _BaseSysConfCrudService_Page_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BaseSysConfCrudService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/base_sys_conf.crud.proto",
}
