// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: app/v1/base_sys_department.crud.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseSysDepartmentCrudService_Add_FullMethodName    = "/api.BaseSysDepartmentCrudService/Add"
	BaseSysDepartmentCrudService_Update_FullMethodName = "/api.BaseSysDepartmentCrudService/Update"
	BaseSysDepartmentCrudService_Info_FullMethodName   = "/api.BaseSysDepartmentCrudService/Info"
	BaseSysDepartmentCrudService_Delete_FullMethodName = "/api.BaseSysDepartmentCrudService/Delete"
	BaseSysDepartmentCrudService_Page_FullMethodName   = "/api.BaseSysDepartmentCrudService/Page"
	BaseSysDepartmentCrudService_List_FullMethodName   = "/api.BaseSysDepartmentCrudService/List"
)

// BaseSysDepartmentCrudServiceClient is the client API for BaseSysDepartmentCrudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseSysDepartmentCrudServiceClient interface {
	// Add
	Add(ctx context.Context, in *BaseSysDepartmentAddRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentAddRpcRes, error)
	// Update
	Update(ctx context.Context, in *BaseSysDepartmentUpdateRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentUpdateRpcRes, error)
	// Info
	Info(ctx context.Context, in *BaseSysDepartmentInfoRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentInfoRpcRes, error)
	// Delete
	Delete(ctx context.Context, in *BaseSysDepartmentDeleteRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentDeleteRpcRes, error)
	// Page
	Page(ctx context.Context, in *BaseSysDepartmentPageRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentPageRpcRes, error)
	// List
	List(ctx context.Context, in *BaseSysDepartmentListRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentListRpcRes, error)
}

type baseSysDepartmentCrudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseSysDepartmentCrudServiceClient(cc grpc.ClientConnInterface) BaseSysDepartmentCrudServiceClient {
	return &baseSysDepartmentCrudServiceClient{cc}
}

func (c *baseSysDepartmentCrudServiceClient) Add(ctx context.Context, in *BaseSysDepartmentAddRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentAddRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentAddRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysDepartmentCrudServiceClient) Update(ctx context.Context, in *BaseSysDepartmentUpdateRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentUpdateRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentUpdateRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysDepartmentCrudServiceClient) Info(ctx context.Context, in *BaseSysDepartmentInfoRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentInfoRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentInfoRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysDepartmentCrudServiceClient) Delete(ctx context.Context, in *BaseSysDepartmentDeleteRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentDeleteRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentDeleteRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysDepartmentCrudServiceClient) Page(ctx context.Context, in *BaseSysDepartmentPageRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentPageRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentPageRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_Page_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseSysDepartmentCrudServiceClient) List(ctx context.Context, in *BaseSysDepartmentListRpcInvoke, opts ...grpc.CallOption) (*BaseSysDepartmentListRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseSysDepartmentListRpcRes)
	err := c.cc.Invoke(ctx, BaseSysDepartmentCrudService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseSysDepartmentCrudServiceServer is the server API for BaseSysDepartmentCrudService service.
// All implementations must embed UnimplementedBaseSysDepartmentCrudServiceServer
// for forward compatibility.
type BaseSysDepartmentCrudServiceServer interface {
	// Add
	Add(context.Context, *BaseSysDepartmentAddRpcInvoke) (*BaseSysDepartmentAddRpcRes, error)
	// Update
	Update(context.Context, *BaseSysDepartmentUpdateRpcInvoke) (*BaseSysDepartmentUpdateRpcRes, error)
	// Info
	Info(context.Context, *BaseSysDepartmentInfoRpcInvoke) (*BaseSysDepartmentInfoRpcRes, error)
	// Delete
	Delete(context.Context, *BaseSysDepartmentDeleteRpcInvoke) (*BaseSysDepartmentDeleteRpcRes, error)
	// Page
	Page(context.Context, *BaseSysDepartmentPageRpcInvoke) (*BaseSysDepartmentPageRpcRes, error)
	// List
	List(context.Context, *BaseSysDepartmentListRpcInvoke) (*BaseSysDepartmentListRpcRes, error)
	mustEmbedUnimplementedBaseSysDepartmentCrudServiceServer()
}

// UnimplementedBaseSysDepartmentCrudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseSysDepartmentCrudServiceServer struct{}

func (UnimplementedBaseSysDepartmentCrudServiceServer) Add(context.Context, *BaseSysDepartmentAddRpcInvoke) (*BaseSysDepartmentAddRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) Update(context.Context, *BaseSysDepartmentUpdateRpcInvoke) (*BaseSysDepartmentUpdateRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) Info(context.Context, *BaseSysDepartmentInfoRpcInvoke) (*BaseSysDepartmentInfoRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) Delete(context.Context, *BaseSysDepartmentDeleteRpcInvoke) (*BaseSysDepartmentDeleteRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) Page(context.Context, *BaseSysDepartmentPageRpcInvoke) (*BaseSysDepartmentPageRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Page not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) List(context.Context, *BaseSysDepartmentListRpcInvoke) (*BaseSysDepartmentListRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) mustEmbedUnimplementedBaseSysDepartmentCrudServiceServer() {
}
func (UnimplementedBaseSysDepartmentCrudServiceServer) testEmbeddedByValue() {}

// UnsafeBaseSysDepartmentCrudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseSysDepartmentCrudServiceServer will
// result in compilation errors.
type UnsafeBaseSysDepartmentCrudServiceServer interface {
	mustEmbedUnimplementedBaseSysDepartmentCrudServiceServer()
}

func RegisterBaseSysDepartmentCrudServiceServer(s grpc.ServiceRegistrar, srv BaseSysDepartmentCrudServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseSysDepartmentCrudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseSysDepartmentCrudService_ServiceDesc, srv)
}

func _BaseSysDepartmentCrudService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentAddRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).Add(ctx, req.(*BaseSysDepartmentAddRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysDepartmentCrudService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentUpdateRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).Update(ctx, req.(*BaseSysDepartmentUpdateRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysDepartmentCrudService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentInfoRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).Info(ctx, req.(*BaseSysDepartmentInfoRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysDepartmentCrudService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentDeleteRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).Delete(ctx, req.(*BaseSysDepartmentDeleteRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysDepartmentCrudService_Page_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentPageRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).Page(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_Page_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).Page(ctx, req.(*BaseSysDepartmentPageRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseSysDepartmentCrudService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSysDepartmentListRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseSysDepartmentCrudServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseSysDepartmentCrudService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseSysDepartmentCrudServiceServer).List(ctx, req.(*BaseSysDepartmentListRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseSysDepartmentCrudService_ServiceDesc is the grpc.ServiceDesc for BaseSysDepartmentCrudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseSysDepartmentCrudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BaseSysDepartmentCrudService",
	HandlerType: (*BaseSysDepartmentCrudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BaseSysDepartmentCrudService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BaseSysDepartmentCrudService_Update_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _BaseSysDepartmentCrudService_Info_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BaseSysDepartmentCrudService_Delete_Handler,
		},
		{
			MethodName: "Page",
			Handler:    _BaseSysDepartmentCrudService_Page_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BaseSysDepartmentCrudService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/base_sys_department.crud.proto",
}
