// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: open/v1/open.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptchaRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty" v:"required"` // v:required
	Widget        int32                  `protobuf:"varint,2,opt,name=Widget,proto3" json:"Widget,omitempty" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRpcInvoke) Reset() {
	*x = CaptchaRpcInvoke{}
	mi := &file_open_v1_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRpcInvoke) ProtoMessage() {}

func (x *CaptchaRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_open_v1_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRpcInvoke.ProtoReflect.Descriptor instead.
func (*CaptchaRpcInvoke) Descriptor() ([]byte, []int) {
	return file_open_v1_open_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaRpcInvoke) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaRpcInvoke) GetWidget() int32 {
	if x != nil {
		return x.Widget
	}
	return 0
}

type CaptchaRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=CaptchaId,proto3" json:"CaptchaId,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRpcRes) Reset() {
	*x = CaptchaRpcRes{}
	mi := &file_open_v1_open_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRpcRes) ProtoMessage() {}

func (x *CaptchaRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_v1_open_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRpcRes.ProtoReflect.Descriptor instead.
func (*CaptchaRpcRes) Descriptor() ([]byte, []int) {
	return file_open_v1_open_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaRpcRes) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaRpcRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LoginRpcInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=CaptchaId,proto3" json:"CaptchaId,omitempty" v:"required"`   // v:required
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty" v:"required"`     // v:required
	Username      string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty" v:"required"`     // v:required
	VerifyCode    string                 `protobuf:"bytes,4,opt,name=VerifyCode,proto3" json:"VerifyCode,omitempty" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRpcInvoke) Reset() {
	*x = LoginRpcInvoke{}
	mi := &file_open_v1_open_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRpcInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRpcInvoke) ProtoMessage() {}

func (x *LoginRpcInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_open_v1_open_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRpcInvoke.ProtoReflect.Descriptor instead.
func (*LoginRpcInvoke) Descriptor() ([]byte, []int) {
	return file_open_v1_open_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRpcInvoke) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *LoginRpcInvoke) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRpcInvoke) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRpcInvoke) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type LoginRpcRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expirea       int64                  `protobuf:"varint,1,opt,name=expirea,proto3" json:"expirea,omitempty"`
	RefreshExpire int64                  `protobuf:"varint,2,opt,name=RefreshExpire,proto3" json:"RefreshExpire,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRpcRes) Reset() {
	*x = LoginRpcRes{}
	mi := &file_open_v1_open_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRpcRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRpcRes) ProtoMessage() {}

func (x *LoginRpcRes) ProtoReflect() protoreflect.Message {
	mi := &file_open_v1_open_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRpcRes.ProtoReflect.Descriptor instead.
func (*LoginRpcRes) Descriptor() ([]byte, []int) {
	return file_open_v1_open_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRpcRes) GetExpirea() int64 {
	if x != nil {
		return x.Expirea
	}
	return 0
}

func (x *LoginRpcRes) GetRefreshExpire() int64 {
	if x != nil {
		return x.RefreshExpire
	}
	return 0
}

func (x *LoginRpcRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginRpcRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshTokenInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty" v:"required"` // v:required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenInvoke) Reset() {
	*x = RefreshTokenInvoke{}
	mi := &file_open_v1_open_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenInvoke) ProtoMessage() {}

func (x *RefreshTokenInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_open_v1_open_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenInvoke.ProtoReflect.Descriptor instead.
func (*RefreshTokenInvoke) Descriptor() ([]byte, []int) {
	return file_open_v1_open_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenInvoke) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_open_v1_open_proto protoreflect.FileDescriptor

const file_open_v1_open_proto_rawDesc = "" +
	"\n" +
	"\x12open/v1/open.proto\x12\fv1.base.open\"B\n" +
	"\x10CaptchaRpcInvoke\x12\x16\n" +
	"\x06Height\x18\x01 \x01(\x05R\x06Height\x12\x16\n" +
	"\x06Widget\x18\x02 \x01(\x05R\x06Widget\"A\n" +
	"\rCaptchaRpcRes\x12\x1c\n" +
	"\tCaptchaId\x18\x01 \x01(\tR\tCaptchaId\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\tR\x04Data\"\x86\x01\n" +
	"\x0eLoginRpcInvoke\x12\x1c\n" +
	"\tCaptchaId\x18\x01 \x01(\tR\tCaptchaId\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\x12\x1e\n" +
	"\n" +
	"VerifyCode\x18\x04 \x01(\tR\n" +
	"VerifyCode\"\x87\x01\n" +
	"\vLoginRpcRes\x12\x18\n" +
	"\aexpirea\x18\x01 \x01(\x03R\aexpirea\x12$\n" +
	"\rRefreshExpire\x18\x02 \x01(\x03R\rRefreshExpire\x12\"\n" +
	"\fRefreshToken\x18\x03 \x01(\tR\fRefreshToken\x12\x14\n" +
	"\x05Token\x18\x04 \x01(\tR\x05Token\"8\n" +
	"\x12RefreshTokenInvoke\x12\"\n" +
	"\fRefreshToken\x18\x01 \x01(\tR\fRefreshToken2\xe1\x01\n" +
	"\bBaseOpen\x12F\n" +
	"\aCaptcha\x12\x1e.v1.base.open.CaptchaRpcInvoke\x1a\x1b.v1.base.open.CaptchaRpcRes\x12@\n" +
	"\x05Login\x12\x1c.v1.base.open.LoginRpcInvoke\x1a\x19.v1.base.open.LoginRpcRes\x12K\n" +
	"\fRefreshToken\x12 .v1.base.open.RefreshTokenInvoke\x1a\x19.v1.base.open.LoginRpcResB>Z<github.com/vera-byte/vgo/app/admin/api/v1/base_open/protobufb\x06proto3"

var (
	file_open_v1_open_proto_rawDescOnce sync.Once
	file_open_v1_open_proto_rawDescData []byte
)

func file_open_v1_open_proto_rawDescGZIP() []byte {
	file_open_v1_open_proto_rawDescOnce.Do(func() {
		file_open_v1_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_open_v1_open_proto_rawDesc), len(file_open_v1_open_proto_rawDesc)))
	})
	return file_open_v1_open_proto_rawDescData
}

var file_open_v1_open_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_open_v1_open_proto_goTypes = []any{
	(*CaptchaRpcInvoke)(nil),   // 0: v1.base.open.CaptchaRpcInvoke
	(*CaptchaRpcRes)(nil),      // 1: v1.base.open.CaptchaRpcRes
	(*LoginRpcInvoke)(nil),     // 2: v1.base.open.LoginRpcInvoke
	(*LoginRpcRes)(nil),        // 3: v1.base.open.LoginRpcRes
	(*RefreshTokenInvoke)(nil), // 4: v1.base.open.RefreshTokenInvoke
}
var file_open_v1_open_proto_depIdxs = []int32{
	0, // 0: v1.base.open.BaseOpen.Captcha:input_type -> v1.base.open.CaptchaRpcInvoke
	2, // 1: v1.base.open.BaseOpen.Login:input_type -> v1.base.open.LoginRpcInvoke
	4, // 2: v1.base.open.BaseOpen.RefreshToken:input_type -> v1.base.open.RefreshTokenInvoke
	1, // 3: v1.base.open.BaseOpen.Captcha:output_type -> v1.base.open.CaptchaRpcRes
	3, // 4: v1.base.open.BaseOpen.Login:output_type -> v1.base.open.LoginRpcRes
	3, // 5: v1.base.open.BaseOpen.RefreshToken:output_type -> v1.base.open.LoginRpcRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_open_v1_open_proto_init() }
func file_open_v1_open_proto_init() {
	if File_open_v1_open_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_open_v1_open_proto_rawDesc), len(file_open_v1_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_open_v1_open_proto_goTypes,
		DependencyIndexes: file_open_v1_open_proto_depIdxs,
		MessageInfos:      file_open_v1_open_proto_msgTypes,
	}.Build()
	File_open_v1_open_proto = out.File
	file_open_v1_open_proto_goTypes = nil
	file_open_v1_open_proto_depIdxs = nil
}
