// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: open/v1/open.proto

package protobuf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseOpen_Captcha_FullMethodName = "/v1.base.open.BaseOpen/Captcha"
	BaseOpen_Login_FullMethodName   = "/v1.base.open.BaseOpen/Login"
)

// BaseOpenClient is the client API for BaseOpen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseOpenClient interface {
	Captcha(ctx context.Context, in *CaptchaRpcInvoke, opts ...grpc.CallOption) (*CaptchaRpcRes, error)
	Login(ctx context.Context, in *LoginRpcInvoke, opts ...grpc.CallOption) (*LoginRpcRes, error)
}

type baseOpenClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseOpenClient(cc grpc.ClientConnInterface) BaseOpenClient {
	return &baseOpenClient{cc}
}

func (c *baseOpenClient) Captcha(ctx context.Context, in *CaptchaRpcInvoke, opts ...grpc.CallOption) (*CaptchaRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptchaRpcRes)
	err := c.cc.Invoke(ctx, BaseOpen_Captcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseOpenClient) Login(ctx context.Context, in *LoginRpcInvoke, opts ...grpc.CallOption) (*LoginRpcRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRpcRes)
	err := c.cc.Invoke(ctx, BaseOpen_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseOpenServer is the server API for BaseOpen service.
// All implementations must embed UnimplementedBaseOpenServer
// for forward compatibility.
type BaseOpenServer interface {
	Captcha(context.Context, *CaptchaRpcInvoke) (*CaptchaRpcRes, error)
	Login(context.Context, *LoginRpcInvoke) (*LoginRpcRes, error)
	mustEmbedUnimplementedBaseOpenServer()
}

// UnimplementedBaseOpenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseOpenServer struct{}

func (UnimplementedBaseOpenServer) Captcha(context.Context, *CaptchaRpcInvoke) (*CaptchaRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Captcha not implemented")
}
func (UnimplementedBaseOpenServer) Login(context.Context, *LoginRpcInvoke) (*LoginRpcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBaseOpenServer) mustEmbedUnimplementedBaseOpenServer() {}
func (UnimplementedBaseOpenServer) testEmbeddedByValue()                  {}

// UnsafeBaseOpenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseOpenServer will
// result in compilation errors.
type UnsafeBaseOpenServer interface {
	mustEmbedUnimplementedBaseOpenServer()
}

func RegisterBaseOpenServer(s grpc.ServiceRegistrar, srv BaseOpenServer) {
	// If the following call pancis, it indicates UnimplementedBaseOpenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseOpen_ServiceDesc, srv)
}

func _BaseOpen_Captcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptchaRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseOpenServer).Captcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseOpen_Captcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseOpenServer).Captcha(ctx, req.(*CaptchaRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseOpen_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRpcInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseOpenServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseOpen_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseOpenServer).Login(ctx, req.(*LoginRpcInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseOpen_ServiceDesc is the grpc.ServiceDesc for BaseOpen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseOpen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.base.open.BaseOpen",
	HandlerType: (*BaseOpenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Captcha",
			Handler:    _BaseOpen_Captcha_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _BaseOpen_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "open/v1/open.proto",
}
